#!/usr/bin/env python3
"""Exact checks for divisor-residue subgroup and cyclic critical examples."""

from __future__ import annotations

import argparse
import json
import math


def is_prime(value: int) -> bool:
    if value < 2:
        return False
    if value % 2 == 0:
        return value == 2
    divisor = 3
    while divisor * divisor <= value:
        if value % divisor == 0:
            return False
        divisor += 2
    return True


def distinct_prime_factors(value: int) -> tuple[int, ...]:
    factors: list[int] = []
    divisor = 2
    while divisor * divisor <= value:
        if value % divisor == 0:
            factors.append(divisor)
            while value % divisor == 0:
                value //= divisor
        divisor = 3 if divisor == 2 else divisor + 2
    if value > 1:
        factors.append(value)
    return tuple(factors)


def smallest_prime_factors(limit: int) -> list[int]:
    """Return a smallest-prime-factor table through limit, inclusive."""
    if limit < 2:
        raise ValueError("limit must be at least two")
    spf = list(range(limit + 1))
    spf[0] = 0
    spf[1] = 1
    for value in range(2, math.isqrt(limit) + 1):
        if spf[value] != value:
            continue
        for multiple in range(value * value, limit + 1, value):
            if spf[multiple] == multiple:
                spf[multiple] = value
    return spf


def factorization_from_spf(
    value: int, smallest_factors: list[int]
) -> tuple[tuple[int, int], ...]:
    """Factor a positive value using an inclusive smallest-factor table."""
    if value < 1 or value >= len(smallest_factors):
        raise ValueError("value must lie in the supplied factor table")
    factors: list[tuple[int, int]] = []
    while value > 1:
        factor = smallest_factors[value]
        exponent = 0
        while value % factor == 0:
            value //= factor
            exponent += 1
        factors.append((factor, exponent))
    return tuple(factors)


def primitive_root_prime(prime: int) -> int:
    """Return the least primitive root of an odd prime."""
    if prime < 3 or not is_prime(prime):
        raise ValueError("prime must be an odd prime")
    order = prime - 1
    factors = distinct_prime_factors(order)
    for candidate in range(2, prime):
        if all(pow(candidate, order // factor, prime) != 1 for factor in factors):
            return candidate
    raise AssertionError("an odd prime must have a primitive root")


def subset_product_residues(sequence: tuple[int, ...], modulus: int) -> frozenset[int]:
    """Return products of all subsequences, including the empty product."""
    if modulus < 2:
        raise ValueError("modulus must be at least two")
    residues = {1 % modulus}
    for value in sequence:
        value %= modulus
        if math.gcd(value, modulus) != 1:
            raise ValueError("every sequence term must be a unit")
        residues.update((residue * value) % modulus for residue in tuple(residues))
    return frozenset(residues)


def subset_sum_residues(sequence: tuple[int, ...], modulus: int) -> frozenset[int]:
    """Additive counterpart used for the sharp cyclic-group example."""
    if modulus < 2:
        raise ValueError("modulus must be at least two")
    residues = {0}
    for value in sequence:
        residues.update((residue + value) % modulus for residue in tuple(residues))
    return frozenset(residues)


def multiplicative_stabilizer(residues: frozenset[int], modulus: int) -> tuple[int, ...]:
    units = [value for value in range(modulus) if math.gcd(value, modulus) == 1]
    return tuple(
        value
        for value in units
        if {(value * residue) % modulus for residue in residues} == set(residues)
    )


def additive_stabilizer(residues: frozenset[int], modulus: int) -> tuple[int, ...]:
    return tuple(
        value
        for value in range(modulus)
        if {(value + residue) % modulus for residue in residues} == set(residues)
    )


def cyclic_subgroup(value: int, modulus: int) -> frozenset[int]:
    if math.gcd(value, modulus) != 1:
        raise ValueError("value must be a unit")
    result = {1}
    current = value % modulus
    while current not in result:
        result.add(current)
        current = current * value % modulus
    return frozenset(result)


def generated_subgroup(generators: frozenset[int], modulus: int) -> frozenset[int]:
    """Return the subgroup of U(modulus) generated by the supplied units."""
    result = frozenset({1})
    for generator in generators:
        cyclic = cyclic_subgroup(generator, modulus)
        result = frozenset(
            left * right % modulus for left in result for right in cyclic
        )
    return result


def unit_square_subgroup(modulus: int) -> frozenset[int]:
    """Return the square subgroup of the unit group modulo modulus."""
    if modulus < 2:
        raise ValueError("modulus must be at least two")
    return frozenset(
        value * value % modulus
        for value in range(modulus)
        if math.gcd(value, modulus) == 1
    )


def unit_power_subgroup(modulus: int, power: int) -> frozenset[int]:
    """Return the power-th subgroup of the unit group modulo modulus."""
    if modulus < 2 or power < 1:
        raise ValueError("modulus must be at least two and power must be positive")
    return frozenset(
        pow(value, power, modulus)
        for value in range(modulus)
        if math.gcd(value, modulus) == 1
    )


def core_prime_residue_subgroup(modulus: int) -> frozenset[int]:
    """Return the residues compatible with primes congruent to one mod 24."""
    if modulus < 2:
        raise ValueError("modulus must be at least two")
    common_modulus = math.gcd(modulus, 24)
    return frozenset(
        value
        for value in range(modulus)
        if math.gcd(value, modulus) == 1 and value % common_modulus == 1
    )


def quadratic_character_coordinates(
    modulus: int,
) -> tuple[tuple[int, ...], dict[int, int]]:
    """Choose coordinates for U(modulus) modulo its square subgroup."""
    if modulus < 2:
        raise ValueError("modulus must be at least two")
    squares = unit_square_subgroup(modulus)

    def representative(value: int) -> int:
        return min(value * square % modulus for square in squares)

    units = tuple(value for value in range(modulus) if math.gcd(value, modulus) == 1)
    representatives = tuple(sorted({representative(value) for value in units}))
    coordinate_by_representative = {1: 0}
    basis: list[int] = []
    for candidate in representatives:
        if candidate in coordinate_by_representative:
            continue
        bit = 1 << len(basis)
        for previous, coordinate in tuple(coordinate_by_representative.items()):
            coordinate_by_representative[
                representative(previous * candidate % modulus)
            ] = coordinate | bit
        basis.append(candidate)
    if len(coordinate_by_representative) != len(representatives):
        raise AssertionError("square quotient coordinates are incomplete")
    return (
        tuple(basis),
        {
            unit: coordinate_by_representative[representative(unit)]
            for unit in units
        },
    )


def active_quadratic_separator_masks(
    support: frozenset[int], modulus: int
) -> tuple[tuple[int, ...], tuple[int, ...]]:
    """Return fixed active quadratic characters that annihilate support."""
    basis, coordinates = quadratic_character_coordinates(modulus)
    target = modulus - 1
    core_residues = core_prime_residue_subgroup(modulus)

    def evaluates_negative(functional: int, value: int) -> bool:
        return (functional & coordinates[value]).bit_count() % 2 == 1

    masks = tuple(
        functional
        for functional in range(1 << len(basis))
        if evaluates_negative(functional, target)
        and not any(evaluates_negative(functional, value) for value in support)
        and any(evaluates_negative(functional, value) for value in core_residues)
    )
    return basis, masks


def target_outside_two_power_depth(
    support: frozenset[int], modulus: int
) -> int | None:
    """Return the largest d with -1 in support times U(modulus)^(2^d)."""
    target = modulus - 1
    if target in support:
        return None
    for depth in range(modulus.bit_length() + 1):
        powers = unit_power_subgroup(modulus, 1 << (depth + 1))
        saturation = {
            left * right % modulus for left in support for right in powers
        }
        if target not in saturation:
            return depth
    raise AssertionError("two-power saturation did not terminate")


def multiplicative_subgroups(modulus: int) -> tuple[frozenset[int], ...]:
    """Enumerate all subgroups of U(modulus); intended for small exact audits."""
    units = tuple(value for value in range(modulus) if math.gcd(value, modulus) == 1)
    identity = frozenset({1})
    seen = {identity}
    queue = [identity]
    while queue:
        subgroup = queue.pop()
        for value in units:
            if value in subgroup:
                continue
            enlarged = generated_subgroup(subgroup | {value}, modulus)
            if enlarged not in seen:
                seen.add(enlarged)
                queue.append(enlarged)
    return tuple(sorted(seen, key=lambda group: (len(group), tuple(sorted(group)))))


def target_free_subgroup_escape_number(
    sequence: tuple[int, ...], modulus: int, target: int
) -> int:
    """Compute the fewest terms outside a subgroup that omits target."""
    candidates = [
        subgroup
        for subgroup in multiplicative_subgroups(modulus)
        if target % modulus not in subgroup
    ]
    if not candidates:
        raise AssertionError("the identity subgroup must omit a nonidentity target")
    return min(sum(value % modulus not in subgroup for value in sequence) for subgroup in candidates)


def cyclic_additive_critical_example(order: int) -> dict[str, object]:
    """Return the C_(2r) example attaining the Kneser exception bound."""
    if order < 4 or order % 2:
        raise ValueError("order must be even and at least four")
    half = order // 2
    sequence = (1,) * (half - 1) + (order - 1,) * (half - 1)
    subsums = subset_sum_residues(sequence, order)
    return {
        "order": order,
        "target": half,
        "sequence": sequence,
        "subsum_residues": subsums,
        "stabilizer": additive_stabilizer(subsums, order),
    }


def unit_group_critical_example(prime: int) -> dict[str, object]:
    """Embed a linear-exception example in U(4q), for q == 3 (mod 4)."""
    if prime < 7 or not is_prime(prime) or prime % 4 != 3:
        raise ValueError("prime must be at least seven and congruent to three mod four")
    modulus = 4 * prime
    root = primitive_root_prime(prime)
    unit = next(
        value
        for value in range(root, modulus, prime)
        if value % 4 == 3
    )
    inverse = pow(unit, -1, modulus)
    half_order = (prime - 1) // 2
    sequence = (unit,) * (half_order - 1) + (inverse,) * (half_order - 1)
    products = subset_product_residues(sequence, modulus)
    generated = cyclic_subgroup(unit, modulus)
    target = modulus - 1
    return {
        "prime": prime,
        "modulus": modulus,
        "group_order": 2 * (prime - 1),
        "target": target,
        "primitive_root_mod_prime": root,
        "unit": unit,
        "inverse": inverse,
        "sequence": sequence,
        "subset_product_residues": products,
        "generated_subgroup": generated,
        "stabilizer": multiplicative_stabilizer(products, modulus),
        "minimum_target_free_subgroup_exceptions": len(sequence),
    }


def least_prime_in_class(residue: int, modulus: int) -> int:
    if math.gcd(residue, modulus) != 1:
        raise ValueError("residue class must be coprime to modulus")
    candidate = residue % modulus
    if candidate < 2:
        candidate += modulus
    while not is_prime(candidate):
        candidate += modulus
    return candidate


def divisor_residues_from_factorization(
    factorization: tuple[tuple[int, int], ...], modulus: int
) -> frozenset[int]:
    residues = {1 % modulus}
    for prime, exponent in factorization:
        if not is_prime(prime) or exponent < 0 or math.gcd(prime, modulus) != 1:
            raise ValueError("factorization must contain unit primes with nonnegative exponents")
        powers = [pow(prime, power, modulus) for power in range(exponent + 1)]
        residues = {
            residue * power % modulus
            for residue in residues
            for power in powers
        }
    return frozenset(residues)


def realized_integer_example(prime: int) -> dict[str, object]:
    example = unit_group_critical_example(prime)
    modulus = int(example["modulus"])
    exponent = (prime - 3) // 2
    positive_prime = least_prime_in_class(int(example["unit"]), modulus)
    negative_prime = least_prime_in_class(int(example["inverse"]), modulus)
    factorization = ((positive_prime, exponent), (negative_prime, exponent))
    residues = divisor_residues_from_factorization(factorization, modulus)
    return {
        **example,
        "factorization": factorization,
        "integer": positive_prime**exponent * negative_prime**exponent,
        "divisor_residues": residues,
    }


def support_critical_ray_analysis(
    prime: int, a: int, c: int, smallest_factors: list[int]
) -> dict[str, object]:
    """Analyze the exact one-hole subgroup stratum of one Type II AC ray."""
    if prime < 2 or a < 1 or c < 1:
        raise ValueError("prime, a, and c must be positive")
    modulus = 4 * a * c
    shifted = prime + 4 * a * a * c
    if shifted >= len(smallest_factors):
        raise ValueError("factor table does not cover the shifted integer")
    if math.gcd(prime, modulus) != 1:
        raise ValueError("prime must be coprime to the ray modulus")

    factorization = factorization_from_spf(shifted, smallest_factors)
    sequence = tuple(
        factor % modulus
        for factor, exponent in factorization
        for _ in range(exponent)
    )
    residues = subset_product_residues(sequence, modulus)
    support = generated_subgroup(frozenset(sequence), modulus)
    target = modulus - 1
    total_product = math.prod(sequence) % modulus
    defect = support - residues
    target_in_support = target in support
    squares = unit_square_subgroup(modulus)
    core_residues = core_prime_residue_subgroup(modulus)
    support_square_saturation = frozenset(
        left * right % modulus for left in support for right in squares
    )
    two_power_depth = target_outside_two_power_depth(support, modulus)
    target_partner = total_product * pow(target, -1, modulus) % modulus
    missing_square_roots = frozenset(
        residue
        for residue in defect
        if residue * residue % modulus == total_product
    )
    failed = target not in residues
    support_critical = (
        failed
        and target_in_support
        and defect == {target}
    )
    return {
        "prime": prime,
        "a": a,
        "c": c,
        "modulus": modulus,
        "shifted": shifted,
        "factorization": factorization,
        "sequence": sequence,
        "residues": residues,
        "support": support,
        "target": target,
        "total_product": total_product,
        "defect": defect,
        "target_in_support": target_in_support,
        "unit_square_subgroup": squares,
        "core_prime_residue_subgroup": core_residues,
        "support_square_saturation": support_square_saturation,
        "target_outside_two_power_depth": two_power_depth,
        "target_quadratically_separable": target not in support_square_saturation,
        "quadratic_separator_core_active": (
            target not in support_square_saturation
            and not core_residues.issubset(support_square_saturation)
        ),
        "target_partner": target_partner,
        "defect_orbit_invariant": all(
            total_product * pow(residue, -1, modulus) % modulus in defect
            for residue in defect
        ),
        "missing_square_roots": missing_square_roots,
        "failed": failed,
        "support_critical": support_critical,
        "nontrivial_two_hole": (
            failed
            and target_in_support
            and total_product != 1
            and len(defect) == 2
        ),
        "two_hole_expected_defect": frozenset({target, target_partner}),
        "nontrivial_odd_defect": (
            failed
            and target_in_support
            and total_product != 1
            and len(defect) % 2 == 1
        ),
        "congruence_forced": not support_critical or prime % modulus == 1,
    }


def run_support_critical_audit(limit: int, ac_bound: int) -> dict[str, object]:
    """Audit failed AC rays and their exact support-critical subfamily."""
    if limit < 73 or ac_bound < 1:
        raise ValueError("limit must be at least 73 and ac_bound must be positive")
    smallest_factors = smallest_prime_factors(limit + 4 * ac_bound**3)
    core_primes = [
        prime
        for prime in range(73, limit + 1)
        if smallest_factors[prime] == prime and prime % 24 == 1
    ]
    ray_failures = 0
    critical: list[dict[str, object]] = []
    congruence_violations: list[dict[str, object]] = []
    target_in_support_failures = 0
    target_outside_support_failures = 0
    target_outside_quadratically_separable = 0
    target_outside_quadratically_inseparable = 0
    target_outside_core_active_quadratic = 0
    target_outside_core_trivial_quadratic = 0
    target_outside_two_power_depth_histogram: dict[int, int] = {}
    active_character_rows: dict[
        tuple[int, int, int, tuple[int, ...]], list[tuple[int, tuple[int, ...]]]
    ] = {}
    defect_histogram: dict[int, int] = {}
    defect_orbit_violations: list[dict[str, int]] = []
    two_hole_count = 0
    two_hole_shape_violations: list[dict[str, object]] = []
    odd_defect_count = 0
    odd_defect_square_violations: list[dict[str, object]] = []
    two_hole_samples: list[dict[str, object]] = []
    odd_defect_samples: list[dict[str, object]] = []
    for prime in core_primes:
        for a in range(1, ac_bound + 1):
            for c in range(1, ac_bound + 1):
                if prime < 4 * a * a * c:
                    continue
                analysis = support_critical_ray_analysis(
                    prime, a, c, smallest_factors
                )
                if not analysis["failed"]:
                    continue
                ray_failures += 1
                if analysis["target_in_support"]:
                    target_in_support_failures += 1
                    defect_size = len(analysis["defect"])
                    defect_histogram[defect_size] = (
                        defect_histogram.get(defect_size, 0) + 1
                    )
                    if not analysis["defect_orbit_invariant"]:
                        defect_orbit_violations.append(
                            {
                                "prime": prime,
                                "a": a,
                                "c": c,
                                "modulus": int(analysis["modulus"]),
                            }
                        )
                else:
                    target_outside_support_failures += 1
                    depth = analysis["target_outside_two_power_depth"]
                    if depth is None:
                        raise AssertionError("target-outside failure must have a depth")
                    target_outside_two_power_depth_histogram[depth] = (
                        target_outside_two_power_depth_histogram.get(depth, 0) + 1
                    )
                    if analysis["target_quadratically_separable"]:
                        target_outside_quadratically_separable += 1
                        if analysis["quadratic_separator_core_active"]:
                            target_outside_core_active_quadratic += 1
                            basis, masks = active_quadratic_separator_masks(
                                analysis["support"], int(analysis["modulus"])
                            )
                            if not masks:
                                raise AssertionError(
                                    "core-active support must have an active character"
                                )
                            key = (a, c, int(analysis["modulus"]), basis)
                            active_character_rows.setdefault(key, []).append(
                                (prime, masks)
                            )
                        else:
                            target_outside_core_trivial_quadratic += 1
                    else:
                        target_outside_quadratically_inseparable += 1
                if not analysis["support_critical"]:
                    record = {
                        key: analysis[key]
                        for key in (
                            "prime",
                            "a",
                            "c",
                            "modulus",
                            "shifted",
                            "factorization",
                            "sequence",
                        )
                    }
                    if analysis["nontrivial_two_hole"]:
                        two_hole_count += 1
                        if analysis["defect"] != analysis["two_hole_expected_defect"]:
                            two_hole_shape_violations.append(record)
                        if len(two_hole_samples) < 10:
                            two_hole_samples.append(
                                {
                                    **record,
                                    "total_product": analysis["total_product"],
                                    "defect": analysis["defect"],
                                }
                            )
                    if analysis["nontrivial_odd_defect"]:
                        odd_defect_count += 1
                        if not analysis["missing_square_roots"]:
                            odd_defect_square_violations.append(record)
                        if len(odd_defect_samples) < 10:
                            odd_defect_samples.append(
                                {
                                    **record,
                                    "total_product": analysis["total_product"],
                                    "defect": analysis["defect"],
                                    "missing_square_roots": analysis[
                                        "missing_square_roots"
                                    ],
                                }
                            )
                    continue
                record = {
                    key: analysis[key]
                    for key in (
                        "prime",
                        "a",
                        "c",
                        "modulus",
                        "shifted",
                        "factorization",
                        "sequence",
                    )
                }
                critical.append(record)
                if not analysis["congruence_forced"]:
                    congruence_violations.append(record)
    active_character_fixedness = []
    for (a, c, modulus, basis), rows in sorted(active_character_rows.items()):
        common_masks = set(rows[0][1])
        all_masks: set[int] = set()
        for _, masks in rows:
            common_masks.intersection_update(masks)
            all_masks.update(masks)
        active_character_fixedness.append(
            {
                "a": a,
                "c": c,
                "modulus": modulus,
                "basis": basis,
                "failure_count": len(rows),
                "available_masks": tuple(sorted(all_masks)),
                "common_masks": tuple(sorted(common_masks)),
                "samples": tuple(rows[:5]),
            }
        )
    return {
        "limit": limit,
        "ac_bound": ac_bound,
        "core_prime_count": len(core_primes),
        "ray_failures": ray_failures,
        "target_in_support_failures": target_in_support_failures,
        "target_outside_support_failures": target_outside_support_failures,
        "target_outside_quadratically_separable": (
            target_outside_quadratically_separable
        ),
        "target_outside_quadratically_inseparable": (
            target_outside_quadratically_inseparable
        ),
        "target_outside_core_active_quadratic": (
            target_outside_core_active_quadratic
        ),
        "target_outside_core_trivial_quadratic": (
            target_outside_core_trivial_quadratic
        ),
        "target_outside_two_power_depth_histogram": (
            target_outside_two_power_depth_histogram
        ),
        "active_quadratic_character_fixedness": active_character_fixedness,
        "support_defect_histogram": defect_histogram,
        "defect_orbit_violations": defect_orbit_violations,
        "support_critical_count": len(critical),
        "support_critical_prime_count": len(
            {int(record["prime"]) for record in critical}
        ),
        "congruence_violations": congruence_violations,
        "nontrivial_two_hole_count": two_hole_count,
        "two_hole_shape_violations": two_hole_shape_violations,
        "nontrivial_odd_defect_count": odd_defect_count,
        "odd_defect_square_violations": odd_defect_square_violations,
        "samples": critical[:10],
        "two_hole_samples": two_hole_samples,
        "odd_defect_samples": odd_defect_samples,
    }


def json_ready(value: object) -> object:
    if isinstance(value, (set, frozenset, tuple, list)):
        return [json_ready(item) for item in value]
    if isinstance(value, dict):
        return {key: json_ready(item) for key, item in value.items()}
    return value


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prime", type=int, default=7)
    parser.add_argument("--audit-limit", type=int)
    parser.add_argument("--ac-bound", type=int, default=5)
    args = parser.parse_args()
    result = (
        run_support_critical_audit(args.audit_limit, args.ac_bound)
        if args.audit_limit is not None
        else realized_integer_example(args.prime)
    )
    print(json.dumps(json_ready(result), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
