#!/usr/bin/env python3
"""Verify the maximum 2-adic target-fiber depth dichotomy."""

from __future__ import annotations

import argparse
from itertools import product
from math import gcd
from typing import Sequence

Element = tuple[int, ...]
Exponent = tuple[int, ...]


def add(left: Element, right: Element, moduli: Sequence[int]) -> Element:
    return tuple((a + b) % modulus for a, b, modulus in zip(left, right, moduli))


def scale(value: Element, multiplier: int, moduli: Sequence[int]) -> Element:
    return tuple((multiplier * coordinate) % modulus for coordinate, modulus in zip(value, moduli))


def negate(value: Element, moduli: Sequence[int]) -> Element:
    return scale(value, -1, moduli)


def image(exponent: Exponent, generators: Sequence[Element], moduli: Sequence[int]) -> Element:
    result = tuple(0 for _ in moduli)
    for coefficient, generator in zip(exponent, generators):
        result = add(result, scale(generator, coefficient, moduli), moduli)
    return result


def box(bounds: Sequence[int]) -> tuple[Exponent, ...]:
    return tuple(product(*(range(-bound, bound + 1) for bound in bounds)))


def order(value: Element, moduli: Sequence[int]) -> int:
    identity = tuple(0 for _ in moduli)
    current = identity
    for exponent in range(1, 1 + 4 * max(moduli)):
        current = add(current, value, moduli)
        if current == identity:
            return exponent
    raise AssertionError("element order exceeds control bound")


def cyclic_depth(coordinate: int, modulus: int) -> int:
    """Return max d with coordinate in 2^d C_modulus, for nonzero coordinate."""
    coordinate %= modulus
    if coordinate == 0 or modulus & (modulus - 1):
        raise AssertionError("depth requires a nonzero residue modulo a power of two")
    depth = 0
    while coordinate % 2 == 0:
        coordinate //= 2
        depth += 1
    return depth


def generated_subgroup_order(values: Sequence[int], modulus: int) -> int:
    """Return the order of the subgroup generated by cyclic residues."""
    divisor = modulus
    for value in values:
        divisor = gcd(divisor, value % modulus)
    return modulus // divisor


def profile(
    *,
    moduli: Sequence[int],
    kernel_modulus: int,
    generators: Sequence[Element],
    bounds: Sequence[int],
    target: Element,
) -> dict[str, object]:
    moduli = tuple(moduli)
    bounds = tuple(bounds)
    if kernel_modulus != moduli[-1] or kernel_modulus & (kernel_modulus - 1):
        raise AssertionError("the control kernel must be the final C_(2^a) coordinate")
    kernel_exponent = kernel_modulus.bit_length() - 1
    top_depth = kernel_exponent - 1
    if len(generators) != len(bounds) or len(target) != len(moduli):
        raise AssertionError("dimension mismatch")
    kernel_elements = tuple(
        tuple([0] * (len(moduli) - 1) + [coordinate])
        for coordinate in range(kernel_modulus)
    )
    identity = tuple(0 for _ in moduli)
    if order(target, moduli) != 2:
        raise AssertionError("target must be an involution")
    if target in kernel_elements:
        target_in_kernel = True
    else:
        target_in_kernel = False

    exponents = box(bounds)
    source_set = {image(exponent, generators, moduli) for exponent in exponents}
    if target in source_set:
        raise AssertionError("control must miss the exact target")
    target_coset = {
        add(target, kernel_element, moduli) for kernel_element in kernel_elements
    }
    if not source_set & target_coset:
        raise AssertionError("target coset must be hit")
    fiber_values = {
        (add(source, negate(target, moduli), moduli)[-1] % kernel_modulus)
        for source in source_set & target_coset
    }
    if 0 in fiber_values:
        raise AssertionError("exact target unexpectedly appeared in source set")
    depths = {value: cyclic_depth(value, kernel_modulus) for value in fiber_values}
    maximum_depth = max(depths.values())
    layer = 1 << (maximum_depth + 1)
    subgroup = {
        tuple([0] * (len(moduli) - 1) + [coordinate])
        for coordinate in range(0, kernel_modulus, layer)
    }
    if (source_set & {
        add(target, subgroup_element, moduli) for subgroup_element in subgroup
    }):
        raise AssertionError("maximum-depth subgroup intersects target fiber")

    quotient_fiber = {
        value % layer for value in fiber_values
    }
    top_digit = 1 << maximum_depth
    if top_digit not in quotient_fiber:
        raise AssertionError("maximum-depth fiber did not produce quotient top digit")
    quotient_strict = maximum_depth < top_depth
    disjoint_levels = tuple(
        level
        for level in range(kernel_exponent + 1)
        if not any(value % (1 << level) == 0 for value in fiber_values)
    )
    if not disjoint_levels or disjoint_levels[0] != maximum_depth + 1:
        raise AssertionError("the maximum-depth subgroup was not the first disjoint dyadic tail")

    fiber_exponents = tuple(
        exponent
        for exponent in exponents
        if image(exponent, generators, moduli) in target_coset
    )
    pairs: list[tuple[Exponent, Exponent]] = []
    fixed: list[Exponent] = []
    unseen = set(fiber_exponents)
    while unseen:
        left = min(unseen)
        right = tuple(-coordinate for coordinate in left)
        if right == left:
            fixed.append(left)
            unseen.remove(left)
            continue
        if right not in unseen:
            raise AssertionError("symmetric box did not give a complete antipodal fiber")
        pairs.append((left, right))
        unseen.remove(left)
        unseen.remove(right)

    pair_receipts: list[dict[str, object]] = []
    for left, right in pairs:
        source = image(left, generators, moduli)
        kernel_offset = add(source, negate(target, moduli), moduli)[-1] % kernel_modulus
        delta = tuple(2 * coordinate for coordinate in left)
        relation = image(delta, generators, moduli)
        expected_relation = tuple(
            [0] * (len(moduli) - 1) + [(2 * kernel_offset) % kernel_modulus]
        )
        if relation != expected_relation:
            raise AssertionError("antipodal relation did not map to twice the fiber offset")
        pair_depth = depths[kernel_offset]
        overflow = tuple(
            max(abs(coordinate) - bound, 0)
            for coordinate, bound in zip(delta, bounds)
        )
        short = not any(overflow)
        if pair_depth < top_depth and relation == identity:
            raise AssertionError("a non-top dyadic offset produced a zero relation")
        if pair_depth < top_depth:
            relation_depth = cyclic_depth(relation[-1], kernel_modulus)
            if relation_depth != pair_depth + 1:
                raise AssertionError("relation depth did not increase by one")
        pair_receipts.append(
            {
                "left": list(left),
                "right": list(right),
                "kernel_offset": kernel_offset,
                "offset_depth": pair_depth,
                "delta": list(delta),
                "relation": list(relation),
                "short_relation": short,
                "overflow": list(overflow),
                "relation_is_zero": relation == identity,
            }
        )

    if target_in_kernel and identity not in {
        image(exponent, generators, moduli)
        for exponent in fiber_exponents
        if exponent == tuple(0 for _ in bounds)
    }:
        raise AssertionError("target-in-kernel control lost its fixed exponent")
    if target_in_kernel and maximum_depth != top_depth:
        raise AssertionError("an involution inside cyclic K must expose the top digit")

    top_depth_values = {
        value for value, depth in depths.items() if depth == maximum_depth
    }
    top_source_classes = {
        tuple(
            list(add(image(exponent, generators, moduli), negate(target, moduli), moduli)[:-1])
            + [
                add(image(exponent, generators, moduli), negate(target, moduli), moduli)[-1]
                % layer
            ]
        )
        for exponent in fiber_exponents
        if (
            add(image(exponent, generators, moduli), negate(target, moduli), moduli)[-1]
            % kernel_modulus
        )
        in top_depth_values
    }
    if top_source_classes != {
        tuple([0] * (len(moduli) - 1) + [top_digit])
    }:
        raise AssertionError("maximum-depth source representations did not deduplicate in the quotient")

    top_rep_by_source: dict[Element, Exponent] = {}
    for exponent in fiber_exponents:
        source = image(exponent, generators, moduli)
        offset = add(source, negate(target, moduli), moduli)[-1] % kernel_modulus
        if depths[offset] == maximum_depth:
            top_rep_by_source.setdefault(source, exponent)
    top_representatives = tuple(top_rep_by_source.values())
    packing_bound = 1 << len(bounds)
    cells: dict[tuple[int, ...], list[Exponent]] = {}
    for exponent in top_representatives:
        cell = tuple(int(coordinate > 0) for coordinate in exponent)
        cells.setdefault(cell, []).append(exponent)

    cluster_cell = min(
        cells,
        key=lambda cell: (-len(cells[cell]), cell),
    )
    cluster_members = tuple(sorted(cells[cluster_cell]))
    cluster_relations: list[dict[str, object]] = []
    cluster_relation_values: list[int] = []
    if len(cluster_members) >= 2:
        cluster_base = cluster_members[0]
        base_source = image(cluster_base, generators, moduli)
        for exponent in cluster_members[1:]:
            delta = tuple(a - b for a, b in zip(exponent, cluster_base))
            if any(abs(coordinate) > bound for coordinate, bound in zip(delta, bounds)):
                raise AssertionError("cluster relation exceeded the exponent budget")
            relation = image(delta, generators, moduli)
            if relation == identity or relation[:-1] != identity[:-1]:
                raise AssertionError("cluster relation did not give a nonzero kernel residue")
            cluster_relation_values.append(relation[-1])
            cluster_relations.append(
                {
                    "exponent": list(exponent),
                    "delta": list(delta),
                    "relation": list(relation),
                }
            )
        cluster_subgroup_order = generated_subgroup_order(
            cluster_relation_values,
            kernel_modulus,
        )
        if cluster_subgroup_order < len(cluster_members):
            raise AssertionError("cluster relation subgroup is smaller than its distinct residues")
        cluster_subgroup_depth = kernel_exponent - (cluster_subgroup_order.bit_length() - 1)
        if cluster_subgroup_depth < maximum_depth + 1:
            raise AssertionError("cluster relation subgroup escaped the maximum-depth layer")
    else:
        cluster_subgroup_order = 1
        cluster_subgroup_depth = None
    cluster = {
        "cell": list(cluster_cell),
        "members": [list(exponent) for exponent in cluster_members],
        "relation_count": len(cluster_relations),
        "relations": cluster_relations,
        "subgroup_order": cluster_subgroup_order,
        "subgroup_depth": cluster_subgroup_depth,
        "status": (
            "DYADIC_RELATION_SUBGROUP_CANDIDATE"
            if len(cluster_members) >= 2
            else "TOP_CLASS_CLUSTER_BOUNDARY"
        ),
        "binary_capacity_lower_bound": (
            (len(cluster_members) - 1).bit_length()
            if cluster_members
            else 0
        ),
    }

    packing_pair: dict[str, object] | None = None
    if len(top_representatives) > packing_bound:
        selected: tuple[Exponent, Exponent] | None = None
        for cell in sorted(cells):
            members = sorted(cells[cell])
            if len(members) >= 2:
                selected = (members[0], members[1])
                break
        if selected is None:
            raise AssertionError("exceeded the sign-cell packing bound without a collision")
        left, right = selected
        delta = tuple(a - b for a, b in zip(left, right))
        if any(abs(coordinate) > bound for coordinate, bound in zip(delta, bounds)):
            raise AssertionError("same-cell collision exceeded the exponent budget")
        relation = image(delta, generators, moduli)
        if relation == identity:
            raise AssertionError("distinct top source images produced a zero packing relation")
        relation_depth = cyclic_depth(relation[-1], kernel_modulus)
        if relation_depth < maximum_depth + 1:
            raise AssertionError("packing relation did not enter the maximum-depth subgroup")
        packing_pair = {
            "left": list(left),
            "right": list(right),
            "delta": list(delta),
            "relation": list(relation),
            "relation_depth": relation_depth,
            "cell": list(tuple(int(coordinate > 0) for coordinate in left)),
        }
    packing_status = (
        "SHORT_DYADIC_LAYER_RELATION"
        if packing_pair is not None
        else "TOP_CLASS_PACKING_BOUNDARY"
    )

    return {
        "kernel_modulus": kernel_modulus,
        "target_in_kernel": target_in_kernel,
        "fiber_values": sorted(fiber_values),
        "fiber_depths": {str(value): depth for value, depth in sorted(depths.items())},
        "maximum_depth": maximum_depth,
        "quotient_layer": layer,
        "quotient_subgroup": sorted(element[-1] for element in subgroup),
        "quotient_strict": quotient_strict,
        "quotient_fiber": sorted(quotient_fiber),
        "top_digit": top_digit,
        "disjoint_levels": list(disjoint_levels),
        "top_depth_values": sorted(top_depth_values),
        "top_source_class_count": len(top_source_classes),
        "top_source_classes": [list(value) for value in sorted(top_source_classes)],
        "top_representative_count": len(top_representatives),
        "top_representatives": [
            {
                "source": list(source),
                "exponent": list(exponent),
            }
            for source, exponent in sorted(top_rep_by_source.items())
        ],
        "packing_bound": packing_bound,
        "top_cell_count": len(cells),
        "cluster": cluster,
        "packing_status": packing_status,
        "packing_pair": packing_pair,
        "fiber_exponent_count": len(fiber_exponents),
        "antipodal_pair_count": len(pairs),
        "fixed_exponents": [list(exponent) for exponent in fixed],
        "pairs": pair_receipts,
        "certificate_type": (
            "DYADIC_TARGET_FIBER_QUOTIENT_DESCENT"
            if quotient_strict
            else "TOP_DYADIC_TARGET_FIBER"
        ),
    }


def verify() -> None:
    common = {
        "moduli": (2, 8),
        "kernel_modulus": 8,
        "target": (1, 0),
    }
    strict = profile(
        generators=((1, 2), (0, 4)),
        bounds=(1, 1),
        **common,
    )
    assert strict["fiber_values"] == [2, 6]
    assert strict["maximum_depth"] == 1
    assert strict["quotient_layer"] == 4
    assert strict["quotient_strict"] is True
    assert strict["quotient_fiber"] == [2]
    assert strict["disjoint_levels"] == [2, 3]
    assert strict["top_depth_values"] == [2, 6]
    assert strict["top_source_class_count"] == 1
    assert strict["packing_status"] == "TOP_CLASS_PACKING_BOUNDARY"
    assert strict["cluster"]["status"] == "DYADIC_RELATION_SUBGROUP_CANDIDATE"
    assert strict["certificate_type"] == "DYADIC_TARGET_FIBER_QUOTIENT_DESCENT"
    assert all(not pair["short_relation"] for pair in strict["pairs"])
    assert all(pair["relation"] == [0, 4] for pair in strict["pairs"])

    short = profile(
        generators=((1, 2),),
        bounds=(2,),
        **common,
    )
    assert short["quotient_strict"] is True
    assert short["pairs"][0]["short_relation"] is True
    assert short["pairs"][0]["relation"] == [0, 4]

    top = profile(
        generators=((1, 4),),
        bounds=(1,),
        **common,
    )
    assert top["fiber_values"] == [4]
    assert top["maximum_depth"] == 2
    assert top["quotient_layer"] == 8
    assert top["quotient_strict"] is False
    assert top["disjoint_levels"] == [3]
    assert top["top_source_class_count"] == 1
    assert top["cluster"]["status"] == "TOP_CLASS_CLUSTER_BOUNDARY"
    assert top["certificate_type"] == "TOP_DYADIC_TARGET_FIBER"
    assert top["pairs"][0]["relation_is_zero"] is True

    in_kernel = profile(
        moduli=(8,),
        kernel_modulus=8,
        generators=((1,),),
        bounds=(1,),
        target=(4,),
    )
    assert in_kernel["target_in_kernel"] is True
    assert in_kernel["maximum_depth"] == 2
    assert in_kernel["fixed_exponents"] == [[0]]
    assert in_kernel["cluster"]["status"] == "TOP_CLASS_CLUSTER_BOUNDARY"
    assert in_kernel["certificate_type"] == "TOP_DYADIC_TARGET_FIBER"

    packed = profile(
        moduli=(2, 16),
        kernel_modulus=16,
        generators=((1, 1), (0, 2)),
        bounds=(2, 2),
        target=(1, 0),
    )
    assert packed["maximum_depth"] == 0
    assert packed["top_representative_count"] > packed["packing_bound"]
    assert packed["top_representative_count"] == 6
    assert len(packed["top_representatives"]) == 6
    assert packed["cluster"]["relation_count"] == 2
    assert packed["cluster"]["subgroup_order"] == 8
    assert packed["cluster"]["status"] == "DYADIC_RELATION_SUBGROUP_CANDIDATE"
    assert packed["cluster"]["binary_capacity_lower_bound"] == 2
    assert packed["packing_status"] == "SHORT_DYADIC_LAYER_RELATION"
    assert packed["packing_pair"] is not None
    assert packed["packing_pair"]["relation_depth"] >= 1
    assert all(
        abs(coordinate) <= bound
        for coordinate, bound in zip(
            packed["packing_pair"]["delta"], (2, 2)
        )
    )

    print("verified maximum-depth dyadic target-fiber dichotomy")
    print(
        {
            "strict_quotient": "C8_to_C4",
            "short_relation": "2z_maps_to_C2_subgroup",
            "top_terminal": "order_two_offset",
            "in_kernel_fixed_point": "z=0_is_allowed_only_in_top_case",
            "packing_relation": "more_than_2^r_top_source_images_force_a_budgeted_relation",
        }
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    if not args.verify:
        parser.error("use --verify")
    verify()


if __name__ == "__main__":
    main()
