#!/usr/bin/env python3
"""Show two short source windows miss linear B=1 escapes that exist globally.

The dense 500M--600M upper-half reselection used every Type I source state
generated by normal forms with m <= 215.  Two of its lower-source records have
no beta=1 B=1 realization in that finite source-state menu.  This script
rebuilds that menu and independently exhausts all linear sources to show that
both primes do have beta=1 B=1 bridges outside the menu.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from fractions import Fraction
import hashlib
import importlib.util
import json
import math
from pathlib import Path
import sys

import sympy


ROOT = Path(__file__).resolve().parents[1]
INPUT = (
    ROOT
    / "reproductions"
    / "type-i-mixed-terminal-dense-upper-b1-reselection-profile-600m-results.json"
)
RESELECTION = (
    ROOT / "reproductions" / "type_i_pminusone_miss_upper_b3_reselection_profile.py"
)
DEFAULT_OUTPUT = (
    ROOT
    / "reproductions"
    / "type-i-fixed-source-window-linear-escape-boundary-600m-results.json"
)

EXPECTED_INPUT_SHA256 = (
    "37b8d3ffc095e527ea9990fe306a74398409db827176a823f5b3e992740492a7"
)
EXPECTED = {
    512_335_849: {
        "window_state_count": 3,
        "window_B1_candidate_beta_values": [9142, 37630, 420637],
        "full_linear_u_bound": 13_067,
        "full_linear_directed_state_count": 87,
        "full_linear_distinct_R_count": 52,
        "full_linear_hit_R": [39, 231],
        "full_linear_hit_directed_state_count": 4,
        "least_gap_linear_witness": (2073, 6337, 39, 5216, 535),
    },
    531_010_489: {
        "window_state_count": 4,
        "window_B1_candidate_beta_values": [5],
        "full_linear_u_bound": 13_303,
        "full_linear_directed_state_count": 99,
        "full_linear_distinct_R_count": 58,
        "full_linear_hit_R": [7, 11, 31, 75],
        "full_linear_hit_directed_state_count": 18,
        "least_gap_linear_witness": (1, 66376311, 7, 467, 267),
    },
}


def load_module(name: str, path: Path):
    """Load one repository helper without relying on an installed package."""
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path.name}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


reselection = load_module("fixed_window_linear_escape_reselection", RESELECTION)


def file_sha256(path: Path) -> str:
    """Return the SHA-256 digest of exact bytes."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_normalization(prime: int, source: int, bridge_factor: int) -> dict[str, int]:
    """Return the unique alpha, beta, gamma normalization of one source state."""
    distance = prime - source
    if distance <= 0 or distance % 2 != 1:
        raise AssertionError("source distance must be positive and odd")
    lambda_value = 4 if distance % 4 == 1 else 2
    if source % lambda_value or bridge_factor % lambda_value:
        raise AssertionError("source normalization lost its two-adic factor")
    u, D = source // lambda_value, bridge_factor // lambda_value
    if u * u % D:
        raise AssertionError("source state failed the normalized square condition")
    common = math.gcd(u, D)
    beta, remainder = divmod(D, common)
    if remainder or common % beta:
        raise AssertionError("source normalization did not factor")
    gamma, alpha = common // beta, u // common
    if (
        source != lambda_value * alpha * beta * gamma
        or bridge_factor != lambda_value * beta * beta * gamma
        or math.gcd(alpha, beta) != 1
    ):
        raise AssertionError("source normalization did not reconstruct")
    return {
        "source_distance": distance,
        "lambda": lambda_value,
        "u": u,
        "D": D,
        "alpha": alpha,
        "beta": beta,
        "gamma": gamma,
    }


def tight_linear_bound(prime: int) -> int:
    """Return the exact u bound from p >= 3u^2 + 2u."""
    bound = (math.isqrt(1 + 3 * prime) - 1) // 3
    while 3 * (bound + 1) ** 2 + 2 * (bound + 1) <= prime:
        bound += 1
    while 3 * bound**2 + 2 * bound > prime:
        bound -= 1
    return bound


def enumerate_full_linear_sources(
    prime: int,
) -> tuple[int, dict[int, list[tuple[int, int]]]]:
    """Exhaust every directed p=a+s+asR linear source using p-u divisors."""
    states_by_R: dict[int, set[tuple[int, int]]] = defaultdict(set)
    bound = tight_linear_bound(prime)
    for u in range(1, bound + 1):
        for source_factor in sympy.divisors(prime - u):
            source_factor = int(source_factor)
            if (source_factor - 1) % u:
                continue
            modulus = (source_factor - 1) // u
            if modulus < 3 or modulus % 4 != 3:
                continue
            other = (prime - u) // source_factor
            if other < u:
                continue
            if prime != u + other + u * other * modulus:
                raise AssertionError("linear source divisor recovery failed")
            if other % 2:
                states_by_R[modulus].add((u, other))
            if u % 2 and u != other:
                states_by_R[modulus].add((other, u))
    return bound, {R: sorted(states) for R, states in sorted(states_by_R.items())}


def linear_B_one_witness(
    prime: int, a: int, s: int, modulus: int, C: int
) -> dict[str, object]:
    """Reconstruct and exactly replay one linear B=1 Type I bridge."""
    source = prime - s
    bridge_factor = s * modulus + 1
    K = (prime * modulus + 1) // 4
    if (
        s % 2 != 1
        or prime != a + s + a * s * modulus
        or source != a * bridge_factor
        or bridge_factor > 4 * K - 2 * modulus
        or K % C
        or (4 * C + 1) % modulus
    ):
        raise AssertionError("linear B=1 witness input is invalid")
    H = K // C
    A, remainder = divmod(H + 1, modulus)
    gap, gap_remainder = divmod(4 * C + 1, modulus)
    if remainder or gap_remainder or not (3 <= gap <= prime - 2):
        raise AssertionError("B=1 normal form did not reconstruct")
    normalization = source_normalization(prime, source, bridge_factor)
    if normalization["beta"] != 1:
        raise AssertionError("linear source did not normalize to beta=1")
    source_term = source * K // bridge_factor
    if (
        source_term != a * K
        or prime != 4 * A * C - gap
        or Fraction(4, prime)
        != Fraction(1, A * C) + Fraction(1, A * C * H) + Fraction(1, prime * K)
        or Fraction(4, source)
        != Fraction(1, source_term) + Fraction(1, A * C) + Fraction(1, A * C * H)
    ):
        raise AssertionError("linear B=1 identities did not replay")
    return {
        "a": a,
        "s": s,
        "R": modulus,
        "E": bridge_factor,
        "source_denominator": source,
        "K": K,
        "C": C,
        "normal_form": [A, 1, C],
        "H": H,
        "m": gap,
        "source_normalization": normalization,
        "source_term": source_term,
    }


def full_linear_B_one_hits(
    prime: int,
) -> tuple[int, dict[int, list[tuple[int, int]]], list[dict[str, object]]]:
    """Enumerate every full linear R and all its B=1 target hits."""
    bound, states_by_R = enumerate_full_linear_sources(prime)
    hits = []
    for modulus, states in states_by_R.items():
        K = (prime * modulus + 1) // 4
        matching_C = [
            int(C) for C in sympy.divisors(K) if (4 * int(C) + 1) % modulus == 0
        ]
        if not matching_C:
            continue
        C = min(matching_C)
        witnesses = [linear_B_one_witness(prime, a, s, modulus, C) for a, s in states]
        hits.append(
            {
                "R": modulus,
                "least_matching_C": C,
                "source_states": [[a, s] for a, s in states],
                "witnesses": witnesses,
            }
        )
    return bound, states_by_R, hits


def window_profile(prime: int, gap_cap: int) -> dict[str, object]:
    """Rebuild every B=1 candidate among the exact finite upper source menu."""
    states, forms_checked, lifts_checked = reselection.upper_source_states(
        prime, gap_cap
    )
    candidates = []
    for state in states:
        source = int(state["source_denominator"])
        bridge_factor = int(state["E"])
        realization = reselection.B_one_realization(prime, source, bridge_factor)
        if realization is None:
            continue
        candidates.append(
            {
                **state,
                "B_one_realization": realization,
                "source_normalization": source_normalization(
                    prime, source, bridge_factor
                ),
            }
        )
    candidates.sort(
        key=lambda candidate: (
            int(candidate["source_normalization"]["beta"]),
            int(candidate["B_one_realization"]["m"]),
            int(candidate["source_distance"]),
            int(candidate["E"]),
        )
    )
    return {
        "gap_cap": gap_cap,
        "state_count": len(states),
        "normal_forms_exhaustively_checked": forms_checked,
        "strict_reverse_lifts_exhaustively_checked": lifts_checked,
        "B_one_candidates": candidates,
    }


def audit_prime(prime: int, gap_cap: int) -> dict[str, object]:
    """Compare the finite source window with the complete linear source spectrum."""
    window = window_profile(prime, gap_cap)
    beta_values = [
        int(candidate["source_normalization"]["beta"])
        for candidate in window["B_one_candidates"]
    ]
    if any(beta == 1 for beta in beta_values):
        raise AssertionError(
            "chosen boundary prime unexpectedly has a window-linear hit"
        )
    bound, states_by_R, full_hits = full_linear_B_one_hits(prime)
    hit_R = [int(hit["R"]) for hit in full_hits]
    directed_hit_count = sum(len(hit["witnesses"]) for hit in full_hits)
    least_gap_witness = min(
        (witness for hit in full_hits for witness in hit["witnesses"]),
        key=lambda witness: (
            int(witness["m"]),
            int(witness["R"]),
            int(witness["a"]),
            int(witness["s"]),
        ),
    )
    expected = EXPECTED[prime]
    observed = {
        "window_state_count": int(window["state_count"]),
        "window_B1_candidate_beta_values": beta_values,
        "full_linear_u_bound": bound,
        "full_linear_directed_state_count": sum(
            len(states) for states in states_by_R.values()
        ),
        "full_linear_distinct_R_count": len(states_by_R),
        "full_linear_hit_R": hit_R,
        "full_linear_hit_directed_state_count": directed_hit_count,
        "least_gap_linear_witness": (
            int(least_gap_witness["a"]),
            int(least_gap_witness["s"]),
            int(least_gap_witness["R"]),
            int(least_gap_witness["C"]),
            int(least_gap_witness["m"]),
        ),
    }
    if observed != expected:
        raise AssertionError("fixed-window versus full-linear profile changed")
    return {
        "prime": prime,
        "window": window,
        "window_has_beta_eq_1_B_one_candidate": False,
        "full_linear_u_bound": bound,
        "full_linear_directed_state_count": observed[
            "full_linear_directed_state_count"
        ],
        "full_linear_distinct_R_count": observed["full_linear_distinct_R_count"],
        "full_linear_B_one_hit_R": hit_R,
        "full_linear_B_one_hit_directed_state_count": directed_hit_count,
        "least_gap_full_linear_B_one_witness": least_gap_witness,
        "full_linear_B_one_hits": full_hits,
    }


def run_audit(path: Path = INPUT) -> dict[str, object]:
    """Run both exact fixed-window versus full-linear comparisons."""
    if file_sha256(path) != EXPECTED_INPUT_SHA256:
        raise AssertionError("dense source-window input hash changed")
    payload = json.loads(path.read_text(encoding="utf-8"))
    gap_cap = int(payload["gap_cap"])
    lower_primes = {int(prime) for prime in payload["stored_lower_B_eq_1_primes"]}
    if set(EXPECTED) - lower_primes:
        raise AssertionError("boundary prime left the dense lower-source input")
    profiles = [audit_prime(prime, gap_cap) for prime in sorted(EXPECTED)]
    return {
        "arithmetic": (
            "for each stated prime, exhaust every upper-half source state generated "
            "by all Type I normal forms and strict reverse lifts through m<=215, "
            "test its exact B=1 realization and source normalization; then exhaust "
            "all p=a+s+asR linear sources by the sharp min(a,s) bound and directly "
            "test every divisor of each induced K"
        ),
        "scope_note": (
            "This is a complete comparison of the stated m<=215 source-state menus "
            "and the full linear source spectra for exactly two frozen primes. It "
            "does not assert that beta=1 is globally necessary or sufficient for "
            "either prime, nor prove the universal mixed terminal selector."
        ),
        "input_artifact": path.name,
        "input_sha256": file_sha256(path),
        "source_window_gap_cap": gap_cap,
        "profiles": profiles,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    result = run_audit(args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(
        json.dumps(
            {
                "profiles": [
                    {
                        "prime": profile["prime"],
                        "window_B1_beta_values": [
                            candidate["source_normalization"]["beta"]
                            for candidate in profile["window"]["B_one_candidates"]
                        ],
                        "full_linear_hit_R": profile["full_linear_B_one_hit_R"],
                    }
                    for profile in result["profiles"]
                ]
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
