#!/usr/bin/env python3
"""Classify B=1 divisor-residue misses as subgroup or finite-product obstructions."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import sympy


ROOT = Path(__file__).resolve().parents[1]
H19 = ROOT / "reproductions" / "type-i-h19-even-source-support-min-1b-results.json"
TAIL = ROOT / "reproductions" / "type-i-tail-reverse-even-source-support-min-500m-results.json"
DEFAULT_OUTPUT = ROOT / "reproductions" / "type-i-source-state-b1-product-boundary-results.json"


def divisors(factors: dict[int, int]) -> list[int]:
    result = [1]
    for factor, exponent in factors.items():
        result = [value * factor**power for value in result for power in range(exponent + 1)]
    return sorted(result)


def generated_subgroup(modulus: int, generators: set[int]) -> set[int]:
    values, pending = {1}, [1]
    while pending:
        value = pending.pop()
        for generator in generators:
            candidate = value * generator % modulus
            if candidate not in values:
                values.add(candidate)
                pending.append(candidate)
    return values


def classify(records: list[dict[str, object]], label: str) -> dict[str, object]:
    misses = []
    for entry in records:
        prime = int(entry["prime"])
        edge = entry["selected_edge"]
        source = int(edge["reverse_two_tail_lift"]["source_denominator"])
        bridge = int(edge["E"])
        offset = prime - source
        R = (bridge - 1) // offset
        K = int(edge["K"])
        if (bridge - 1) % offset or 4 * K != prime * R + 1 or K % R != pow(4, -1, R):
            raise AssertionError("invalid source-state residue data")
        target = -pow(4, -1, R) % R
        factors = {int(factor): int(exponent) for factor, exponent in sympy.factorint(K).items()}
        divisor_hit = any(divisor % R == target for divisor in divisors(factors))
        if divisor_hit:
            continue
        subgroup = generated_subgroup(R, {factor % R for factor in factors})
        kind = "finite_product" if target in subgroup else "subgroup"
        misses.append(
            {
                "prime": prime,
                "R": R,
                "target_residue": target,
                "factor_count": len(factors),
                "classification": kind,
            }
        )
    subgroup_count = sum(entry["classification"] == "subgroup" for entry in misses)
    return {
        "label": label,
        "input_count": len(records),
        "B_eq_1_miss_count": len(misses),
        "subgroup_obstruction_count": subgroup_count,
        "finite_product_obstruction_count": len(misses) - subgroup_count,
        "misses": misses,
    }


def run_audit(h19: dict[str, object], tail: dict[str, object]) -> dict[str, object]:
    if len(h19["records"]) != 664 or len(tail["records"]) != 1717:
        raise AssertionError("inputs do not match the stored H19 and 500M bridge profiles")
    h19_profile = classify(h19["records"], "H19-1B")
    tail_profile = classify(tail["records"], "tail-500M")
    if h19_profile["B_eq_1_miss_count"] != 17 or tail_profile["B_eq_1_miss_count"] != 72:
        raise AssertionError("B=1 miss counts diverged from the realization audits")
    return {
        "arithmetic": (
            "for every B=1 source-state miss, enumerate all divisors of K for the target -1/4 (mod R), "
            "then enumerate the multiplicative subgroup generated by the prime-factor residues of K"
        ),
        "scope_note": (
            "A finite structural classification of B=1 misses on two stored bridge profiles. It does not "
            "classify arbitrary source states or prove a global finite-product theorem."
        ),
        "profiles": [h19_profile, tail_profile],
        "total_B_eq_1_miss_count": h19_profile["B_eq_1_miss_count"] + tail_profile["B_eq_1_miss_count"],
        "total_subgroup_obstruction_count": (
            h19_profile["subgroup_obstruction_count"] + tail_profile["subgroup_obstruction_count"]
        ),
        "total_finite_product_obstruction_count": (
            h19_profile["finite_product_obstruction_count"] + tail_profile["finite_product_obstruction_count"]
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--h19", type=Path, default=H19)
    parser.add_argument("--tail", type=Path, default=TAIL)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    result = run_audit(
        json.loads(args.h19.read_text(encoding="utf-8")),
        json.loads(args.tail.read_text(encoding="utf-8")),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({key: value for key, value in result.items() if key != "profiles"}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
