#!/usr/bin/env python3
"""Separate zero-overflow failures into subgroup and finite-exponent obstructions."""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path

import sympy


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "reproductions" / "type-ii-h19-bounded-r-overflow-profile-1b-results.json"
DEFAULT_OUTPUT = ROOT / "reproductions" / "type-ii-h19-zero-overflow-subgroup-profile-1b-results.json"


def generated_subgroup(primes: list[int], modulus: int) -> set[int]:
    """Return the multiplicative subgroup generated by prime residues modulo modulus."""
    residues = {1}
    frontier = [1]
    while frontier:
        residue = frontier.pop()
        for prime in primes:
            product = residue * prime % modulus
            if product not in residues:
                residues.add(product)
                frontier.append(product)
    return residues


def run_audit(payload: dict[str, object]) -> dict[str, object]:
    """Classify every stored first-r state relative to the ordinary -1 divisor target."""
    records = []
    for record in payload["records"]:
        prime, r = int(record["prime"]), int(record["r"])
        m1 = (r * prime + 1) // 4
        prime_support = sorted(int(factor) for factor in sympy.factorint(m1))
        subgroup = generated_subgroup(prime_support, r)
        target_in_subgroup = (r - 1) in subgroup
        if int(record["minimum_overflow"]) == 1:
            kind = "ordinary_divisor_hit"
        elif target_in_subgroup:
            kind = "finite_exponent_obstruction"
        else:
            kind = "subgroup_obstruction"
        records.append(
            {
                "prime": prime,
                "r": r,
                "minimum_overflow": int(record["minimum_overflow"]),
                "prime_support_size": len(prime_support),
                "generated_subgroup_size": len(subgroup),
                "target_minus_one_in_subgroup": target_in_subgroup,
                "classification": kind,
            }
        )
    counts = Counter(record["classification"] for record in records)
    return {
        "arithmetic": (
            "exact factorization of M1, closure of its prime residues in the unit group "
            "modulo r, and comparison of -1 with the actual ordinary-divisor hit profile"
        ),
        "scope_note": (
            "A finite classification of stored first-r states. It does not establish a "
            "subgroup or exponent-saturation theorem for general even-source tails."
        ),
        "prime_limit": payload["prime_limit"],
        "first_hit_count": len(records),
        "classification_counts": dict(sorted(counts.items())),
        "all_positive_overflow_states_have_target_in_subgroup": all(
            record["target_minus_one_in_subgroup"]
            for record in records
            if record["minimum_overflow"] > 1
        ),
        "records": records,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    result = run_audit(json.loads(args.input.read_text(encoding="utf-8")))
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({key: value for key, value in result.items() if key != "records"}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
