#!/usr/bin/env python3
"""Reproduce the canonical Type II fan escape trichotomy.

For a canonical shift s=a^2*c, factor N=p+4*s and compare the divisor
residue set with the subgroup generated by its prime residues modulo 4*a*c.
The exact classes are: a direct Type II hit, a support-outside failure, a
support-inside failure with at least two missing residues, or the one-hole
critical stratum.  A primorial bound rules out an all-one-hole fan.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    ROOT / "reproductions" / "type-ii-canonical-fan-escape-trichotomy-results.json"
)
FOCUSED_PRIMES = (73, 97, 193, 241, 5281, 15601, 16633)
EDGE_CASES = ((97, 16),)


def is_prime(value: int) -> bool:
    if value < 2:
        return False
    if value % 2 == 0:
        return value == 2
    divisor = 3
    while divisor * divisor <= value:
        if value % divisor == 0:
            return False
        divisor += 2
    return True


def smallest_prime_factors(limit: int) -> list[int]:
    spf = list(range(limit + 1))
    if limit >= 0:
        spf[0] = 0
    if limit >= 1:
        spf[1] = 1
    for value in range(2, math.isqrt(limit) + 1):
        if spf[value] != value:
            continue
        for multiple in range(value * value, limit + 1, value):
            if spf[multiple] == multiple:
                spf[multiple] = value
    return spf


def factorization(value: int, spf: list[int]) -> tuple[tuple[int, int], ...]:
    if value < 1 or value >= len(spf):
        raise ValueError("factorization value is outside the SPF table")
    factors: list[tuple[int, int]] = []
    while value > 1:
        prime = spf[value]
        exponent = 0
        while value % prime == 0:
            value //= prime
            exponent += 1
        factors.append((prime, exponent))
    return tuple(factors)


def canonical_pair(shift: int, spf: list[int]) -> tuple[int, int]:
    factors = factorization(shift, spf)
    a = math.prod(prime ** (exponent // 2) for prime, exponent in factors)
    c = math.prod(prime for prime, exponent in factors if exponent % 2)
    if a * a * c != shift or any(
        exponent != 1 for _, exponent in factorization(c, spf)
    ):
        raise AssertionError("canonical square-free decomposition changed")
    return a, c


def subset_product_residues(
    factors: tuple[tuple[int, int], ...], modulus: int
) -> frozenset[int]:
    residues = {1 % modulus}
    for prime, exponent in factors:
        residues = {
            residue * pow(prime, power, modulus) % modulus
            for residue in residues
            for power in range(exponent + 1)
        }
    return frozenset(residues)


def generated_subgroup(
    factors: tuple[tuple[int, int], ...], modulus: int
) -> frozenset[int]:
    generators = {prime % modulus for prime, _ in factors}
    reached = {1 % modulus}
    pending = [1 % modulus]
    while pending:
        value = pending.pop()
        for generator in generators:
            candidate = value * generator % modulus
            if candidate not in reached:
                reached.add(candidate)
                pending.append(candidate)
    return frozenset(reached)


def unit_square_subgroup(modulus: int) -> frozenset[int]:
    return frozenset(
        value * value % modulus
        for value in range(modulus)
        if math.gcd(value, modulus) == 1
    )


def quadratic_coordinates(modulus: int) -> tuple[tuple[int, ...], dict[int, int]]:
    """Coordinate U(modulus)/U(modulus)^2 as an elementary 2-group."""
    squares = unit_square_subgroup(modulus)

    def representative(value: int) -> int:
        return min(value * square % modulus for square in squares)

    units = tuple(value for value in range(modulus) if math.gcd(value, modulus) == 1)
    representatives = tuple(sorted({representative(value) for value in units}))
    coordinates = {1: 0}
    basis: list[int] = []
    for candidate in representatives:
        if candidate in coordinates:
            continue
        bit = 1 << len(basis)
        for previous, coordinate in tuple(coordinates.items()):
            coordinates[representative(previous * candidate % modulus)] = coordinate | bit
        basis.append(candidate)
    if len(coordinates) != len(representatives):
        raise AssertionError("quadratic quotient coordinates are incomplete")
    return tuple(basis), {
        unit: coordinates[representative(unit)] for unit in units
    }


def quadratic_separator(
    support: frozenset[int], modulus: int
) -> dict[str, object] | None:
    """Return a quadratic character trivial on support and negative at -1."""
    basis, coordinates = quadratic_coordinates(modulus)
    target = modulus - 1

    def odd(mask: int, value: int) -> bool:
        return (mask & coordinates[value]).bit_count() % 2 == 1

    masks = [
        mask
        for mask in range(1 << len(basis))
        if odd(mask, target) and all(not odd(mask, value) for value in support)
    ]
    if not masks:
        return None
    mask = min(masks)
    return {
        "character_type": "quadratic",
        "basis_residues": list(basis),
        "functional_mask": mask,
        "character_order": 2,
        "target_phase": -1,
        "annihilates_support": True,
        "separator_count": len(masks),
    }


def canonical_fan_bound(prime: int) -> tuple[int, int]:
    primorial = 1
    for bound in range(2, prime):
        if is_prime(bound):
            primorial *= bound
        if 4 * bound < prime and 4 * primorial > prime - 1:
            return bound, primorial
    raise AssertionError("canonical fan bound was not found")


def ray_record(prime: int, shift: int, spf: list[int]) -> dict[str, object]:
    a, c = canonical_pair(shift, spf)
    modulus = 4 * a * c
    shifted = prime + 4 * a * a * c
    factors = factorization(shifted, spf)
    divisor_residues = subset_product_residues(factors, modulus)
    support = generated_subgroup(factors, modulus)
    target = modulus - 1
    defect = sorted(support - divisor_residues)
    separator = None
    if target in divisor_residues:
        classification = "direct_type_ii"
    elif target not in support:
        separator = quadratic_separator(support, modulus)
        classification = (
            "support_outside_quadratically_separable"
            if separator is not None
            else "support_outside_quadratically_inseparable"
        )
    elif len(defect) >= 2:
        classification = "support_inside_multi_hole"
    else:
        classification = "one_hole_critical"

    return {
        "shift": shift,
        "canonical_parameters": {"A": a, "C": c, "modulus": modulus},
        "shifted_integer": shifted,
        "factorization": [[prime_factor, exponent] for prime_factor, exponent in factors],
        "target": target,
        "divisor_residue_count": len(divisor_residues),
        "support_size": len(support),
        "defect": defect,
        "target_in_divisor_residues": target in divisor_residues,
        "target_in_support": target in support,
        "classification": classification,
        "quadratic_separator": separator,
    }


def fan_profile(prime: int) -> dict[str, object]:
    if not is_prime(prime) or prime % 24 != 1:
        raise ValueError("profile requires a core prime")
    fan_bound, primorial = canonical_fan_bound(prime)
    max_shifted = prime + 4 * fan_bound
    spf = smallest_prime_factors(max_shifted)
    rays = [ray_record(prime, shift, spf) for shift in range(1, fan_bound + 1)]
    counts: dict[str, int] = {}
    for ray in rays:
        classification = str(ray["classification"])
        counts[classification] = counts.get(classification, 0) + 1
    noncritical = sum(
        counts.get(classification, 0)
        for classification in (
            "direct_type_ii",
            "support_outside_quadratically_separable",
            "support_outside_quadratically_inseparable",
            "support_inside_multi_hole",
        )
    )
    if noncritical == 0:
        raise AssertionError("primorial fan unexpectedly stayed in one-hole class")
    prime_ray_checks = [
        {
            "prime_shift": shift,
            "modulus": 4 * canonical_pair(shift, spf)[0] * canonical_pair(shift, spf)[1],
            "one_hole_congruence_required": "p=1 mod 4*ell",
            "observed_prime_congruence": prime
            % (4 * shift)
            if is_prime(shift)
            else None,
        }
        for shift in range(2, fan_bound + 1)
        if is_prime(shift)
    ]
    return {
        "prime": prime,
        "fan_bound": fan_bound,
        "primorial": primorial,
        "fan_conditions": {
            "four_H_less_than_p": 4 * fan_bound < prime,
            "four_primorial_greater_than_p_minus_one": 4 * primorial > prime - 1,
            "verified": 4 * fan_bound < prime and 4 * primorial > prime - 1,
        },
        "rays": rays,
        "classification_counts": counts,
        "noncritical_ray_count": noncritical,
        "one_hole_only_forbidden": True,
        "theorem_conclusion": (
            "direct hit or support-outside separator or support-inside multi-hole"
        ),
        "prime_shift_congruence_checks": prime_ray_checks,
        "selector_status": "analysis_evidence",
        "certificate_type": "type_ii_canonical_fan_escape_trichotomy",
        "recursive_edge_eligible": False,
        "e1_e5": {f"E{i}": False for i in range(1, 6)},
        "proof_boundary": "fan_trichotomy_dual_prefilter",
        "scope_note": (
            "The fan theorem removes the all-one-hole failure stratum. Support-outside "
            "rows carry an exact quadratic separator; multi-hole rows carry a target-fiber "
            "defect. Neither receipt supplies a cross-state lift or recursive descent."
        ),
    }


def build_results(primes: tuple[int, ...] = FOCUSED_PRIMES) -> dict[str, object]:
    profiles = [fan_profile(prime) for prime in primes]
    edge_cases = []
    for prime, shift in EDGE_CASES:
        spf = smallest_prime_factors(prime + 4 * shift)
        ray = ray_record(prime, shift, spf)
        edge_cases.append({"prime": prime, "shift": shift, "ray": ray})
    return {
        "schema_version": "type-ii-canonical-fan-escape-trichotomy/v1",
        "arithmetic": "exact SPF factorization, divisor residues, subgroup closure, and quadratic character separation",
        "profiles": profiles,
        "profile_count": len(profiles),
        "edge_cases": edge_cases,
        "scope_note": (
            "Focused typed replay of the canonical fan theorem. The theorem is general, "
            "while factorization and class counts here cover only the listed primes."
        ),
    }


def verify_results(payload: dict[str, object]) -> None:
    if payload.get("schema_version") != "type-ii-canonical-fan-escape-trichotomy/v1":
        raise AssertionError("fan trichotomy schema changed")
    profiles = payload.get("profiles")
    if not isinstance(profiles, list) or len(profiles) != len(FOCUSED_PRIMES):
        raise AssertionError("fan trichotomy profile count changed")
    for expected_prime, stored in zip(FOCUSED_PRIMES, profiles):
        if not isinstance(stored, dict) or stored.get("prime") != expected_prime:
            raise AssertionError("fan trichotomy prime list changed")
        expected = fan_profile(expected_prime)
        if stored != expected:
            raise AssertionError(f"fan trichotomy profile is stale for p={expected_prime}")
        if stored.get("selector_status") != "analysis_evidence":
            raise AssertionError("fan trichotomy crossed status boundary")
        if stored.get("recursive_edge_eligible") is not False:
            raise AssertionError("fan trichotomy became recursive")
        if stored.get("e1_e5") != {f"E{i}": False for i in range(1, 6)}:
            raise AssertionError("fan trichotomy has an E1-E5 witness")
        for ray in stored["rays"]:
            if ray["classification"] == "support_outside_quadratically_separable":
                separator = ray.get("quadratic_separator")
                if not isinstance(separator, dict) or separator.get(
                    "annihilates_support"
                ) is not True:
                    raise AssertionError("support-outside separator changed")
    edge_cases = payload.get("edge_cases")
    if not isinstance(edge_cases, list) or len(edge_cases) != len(EDGE_CASES):
        raise AssertionError("fan trichotomy edge-case count changed")
    for expected, stored in zip(EDGE_CASES, edge_cases):
        if not isinstance(stored, dict) or (stored.get("prime"), stored.get("shift")) != expected:
            raise AssertionError("fan trichotomy edge-case identity changed")
        ray = stored.get("ray")
        if not isinstance(ray, dict) or ray.get("classification") != "support_outside_quadratically_inseparable":
            raise AssertionError("quadratic-inseparable support-outside boundary changed")
        if ray.get("quadratic_separator") is not None:
            raise AssertionError("quadratic-inseparable ray unexpectedly has a separator")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    payload = build_results()
    rendered = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    if args.verify:
        stored = json.loads(args.output.read_text(encoding="utf-8"))
        verify_results(stored)
        if stored != payload:
            raise SystemExit("stored fan trichotomy result is stale")
        print("verified", args.output)
        return
    args.output.write_text(rendered, encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
