#!/usr/bin/env python3
"""Profile deterministic Type I adaptive escape depths on finite seed states."""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHORT_CERTIFICATE = ROOT / "reproductions" / "short_certificate.py"
ADAPTIVE = ROOT / "reproductions" / "type_i_moving_window_adaptive_escape.py"
RESULTS = (
    ROOT / "reproductions" / "type-i-adaptive-escape-seed-profile-10m-j100-results.json"
)
DEFAULT_LIMIT = 10_000_000
DEFAULT_TARGET_WINDOW = 100
DEFAULT_MAX_DEPTH = 8


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path.name}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


short_certificate = load_module(
    "type_i_adaptive_escape_seed_profile_short_certificate", SHORT_CERTIFICATE
)
adaptive = load_module(
    "type_i_adaptive_escape_seed_profile_adaptive", ADAPTIVE
)


def initial_failure_seeds(limit: int) -> list[int]:
    """Return core primes failing every Type I gap through 31."""
    spf = short_certificate.smallest_prime_factors(limit + 32)
    seeds: list[int] = []
    for prime in short_certificate.primes_up_to(limit):
        if prime % 24 != 1:
            continue
        if all(
            short_certificate.type_i_residue_certificate(prime, gap, spf) is None
            for gap in range(3, 32, 4)
        ):
            seeds.append(prime)
    return seeds


def generated_subgroup(modulus: int, generators: list[int]) -> frozenset[int]:
    """Return the subgroup of unit residues generated by the supplied values."""
    subgroup = {1}
    changed = True
    while changed:
        changed = False
        for left in tuple(subgroup):
            for right in generators:
                product = left * right % modulus
                if product not in subgroup:
                    subgroup.add(product)
                    changed = True
    return frozenset(subgroup)


def multiplicative_order(residue: int, modulus: int) -> int:
    """Return the order of a unit residue modulo modulus."""
    value = 1
    for exponent in range(1, modulus + 1):
        value = value * residue % modulus
        if value == 1:
            return exponent
    raise AssertionError("unit order exceeded the modulus")


def run_profile(
    limit: int = DEFAULT_LIMIT,
    target_window: int = DEFAULT_TARGET_WINDOW,
    max_depth: int = DEFAULT_MAX_DEPTH,
) -> dict[str, object]:
    """Profile the first-residue adaptive chain for every finite seed."""
    if limit < 73:
        raise ValueError("limit must be at least 73")
    if target_window < 8:
        raise ValueError("target_window must be at least 8")
    seeds = initial_failure_seeds(limit)
    records: list[dict[str, object]] = []
    total_subgroup_obstructed_positions = 0
    total_bounded_product_positions = 0
    bounded_breakdown = Counter()
    translate_index_breakdown = Counter()
    for seed in seeds:
        result = adaptive.run_audit(seed, target_window, max_depth)
        closure = result["one_private_prime_closure"]
        fixed_factor_omegas = [
            len(adaptive.model.prime_factorization(row["fixed_factor"]))
            for row in result["conditional_escape"]["rows"]
        ]
        subgroup_obstructed_position_count = 0
        bounded_product_position_count = 0
        for row in result["conditional_escape"]["rows"]:
            generators = [
                prime % row["gap"]
                for prime, _ in adaptive.model.prime_factorization(
                    row["fixed_factor"]
                )
            ]
            generators.append(row["cofactor_residue"])
            subgroup = generated_subgroup(row["gap"], generators)
            if row["target"] in subgroup:
                bounded_product_position_count += 1
                factorization = adaptive.model.prime_factorization(
                    row["fixed_factor"]
                )
                collision_subgroup = generated_subgroup(
                    row["gap"], [prime % row["gap"] for prime, _ in factorization]
                )
                fixed_square_residues = adaptive.model.square_divisor_residues(
                    factorization, row["gap"]
                )
                saturated = fixed_square_residues == collision_subgroup
                quotient_order = next(
                    exponent
                    for exponent in range(1, row["gap"] + 1)
                    if pow(row["cofactor_residue"], exponent, row["gap"])
                    in collision_subgroup
                )
                if saturated and quotient_order <= 3:
                    raise AssertionError(
                        "three-coset saturation would have produced Type I"
                    )
                bounded_breakdown[
                    (
                        "saturated"
                        if saturated
                        else "unsaturated",
                        "quotient_order_at_most_three"
                        if quotient_order <= 3
                        else "quotient_order_at_least_four",
                    )
                ] += 1
                private_order = multiplicative_order(
                    row["cofactor_residue"], row["gap"]
                )
                translate_index = next(
                    (
                        exponent
                        for exponent in range(private_order)
                        if row["target"]
                        in {
                            residue
                            * pow(
                                row["cofactor_residue"], exponent, row["gap"]
                            )
                            % row["gap"]
                            for residue in fixed_square_residues
                        }
                    ),
                    None,
                )
                if translate_index == 3:
                    translate_index_breakdown["index_three"] += 1
                elif translate_index is None:
                    translate_index_breakdown["no_private_translate"] += 1
                else:
                    if translate_index < 3:
                        raise AssertionError(
                            "one-private Type I failure had a usable translate"
                        )
                    translate_index_breakdown["index_at_least_four"] += 1
            else:
                subgroup_obstructed_position_count += 1
        total_subgroup_obstructed_positions += subgroup_obstructed_position_count
        total_bounded_product_positions += bounded_product_position_count
        records.append(
            {
                "seed_prime": seed,
                "completed_window": result["completed_window"],
                "terminal_gap": None if closure is None else closure["gap"],
                "closed_within_target": closure is not None,
                "maximum_fixed_factor_distinct_prime_count": max(
                    fixed_factor_omegas, default=0
                ),
                "additional_local_split_count": sum(
                    max(0, len(extension["path"]) - 1)
                    for extension in result["extensions"]
                ),
                "subgroup_obstructed_position_count": (
                    subgroup_obstructed_position_count
                ),
                "bounded_product_position_count": bounded_product_position_count,
            }
        )
    depth_counts = Counter(record["completed_window"] for record in records)
    long_chain_records = [
        record for record in records if record["completed_window"] >= 50
    ]
    return {
        "arithmetic": (
            "complete Type I scans through m=31 to select seeds, then exact "
            "one-private-prime divisor-residue and local-admissibility checks "
            "along the deterministic first-residue adaptive branch"
        ),
        "scope_note": (
            "A finite, deterministic-branch profile. A terminal point closes "
            "only that selected one-private-prime branch; it does not exclude "
            "other branches, more private factors, or a longer escape."
        ),
        "prime_limit": limit,
        "target_window": target_window,
        "max_split_depth": max_depth,
        "seed_count": len(seeds),
        "closed_within_target_count": sum(
            record["closed_within_target"] for record in records
        ),
        "surviving_seed_primes": [
            record["seed_prime"]
            for record in records
            if not record["closed_within_target"]
        ],
        "completed_window_counts": {
            str(window): depth_counts[window] for window in sorted(depth_counts)
        },
        "maximum_completed_window": max(
            (record["completed_window"] for record in records), default=None
        ),
        "long_chain_complexity_minima": {
            "window_threshold": 50,
            "seed_count": len(long_chain_records),
            "minimum_maximum_fixed_factor_distinct_prime_count": min(
                (
                    record["maximum_fixed_factor_distinct_prime_count"]
                    for record in long_chain_records
                ),
                default=None,
            ),
            "minimum_additional_local_split_count": min(
                (
                    record["additional_local_split_count"]
                    for record in long_chain_records
                ),
                default=None,
            ),
        },
        "failure_mechanism_counts": {
            "subgroup_obstructed_positions": total_subgroup_obstructed_positions,
            "bounded_product_positions": total_bounded_product_positions,
        },
        "bounded_product_breakdown": {
            "unsaturated_quotient_order_at_most_three": bounded_breakdown[
                ("unsaturated", "quotient_order_at_most_three")
            ],
            "unsaturated_quotient_order_at_least_four": bounded_breakdown[
                ("unsaturated", "quotient_order_at_least_four")
            ],
            "saturated_quotient_order_at_least_four": bounded_breakdown[
                ("saturated", "quotient_order_at_least_four")
            ],
        },
        "bounded_product_translate_index_breakdown": {
            "index_three": translate_index_breakdown["index_three"],
            "index_at_least_four": translate_index_breakdown[
                "index_at_least_four"
            ],
            "no_private_translate": translate_index_breakdown[
                "no_private_translate"
            ],
        },
        "records": records,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=DEFAULT_LIMIT)
    parser.add_argument("--target-window", type=int, default=DEFAULT_TARGET_WINDOW)
    parser.add_argument("--max-depth", type=int, default=DEFAULT_MAX_DEPTH)
    parser.add_argument("--output", type=Path, default=RESULTS)
    args = parser.parse_args()
    payload = run_profile(args.limit, args.target_window, args.max_depth)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
