#!/usr/bin/env python3
"""Classify the two half-factor supports in cross-essential zero-overflow states."""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path

import sympy


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "reproductions" / "type-ii-h19-zero-overflow-half-factor-pair-profile-1b-results.json"
DEFAULT_OUTPUT = ROOT / "reproductions" / "type-ii-h19-cross-half-factor-subgroup-profile-1b-results.json"


def generated_subgroup(primes: list[int], modulus: int) -> set[int]:
    """Return the multiplicative subgroup generated by the supplied residues."""
    residues = {1}
    frontier = [1]
    while frontier:
        residue = frontier.pop()
        for prime in primes:
            successor = residue * prime % modulus
            if successor not in residues:
                residues.add(successor)
                frontier.append(successor)
    return residues


def side_supports_target(value: int, r: int) -> tuple[bool, int, int, int, bool]:
    """Return subgroup target status, support/group/divisor sizes, and subgroup saturation."""
    support = sorted(int(q) for q in sympy.factorint(value))
    subgroup = generated_subgroup(support, r)
    divisor_residues = {int(divisor) % r for divisor in sympy.divisors(value)}
    return r - 1 in subgroup, len(support), len(subgroup), len(divisor_residues), divisor_residues == subgroup


def omega(value: int) -> int:
    """Return the prime-factor multiplicity Omega(value)."""
    return sum(int(exponent) for exponent in sympy.factorint(value).values())


def minimum_transporter_omega(support_side: int, external_side: int, r: int) -> tuple[int, int]:
    """Find the least-complexity external divisor beta moving the target into Div(support_side)."""
    support_residues = {int(divisor) % r for divisor in sympy.divisors(support_side)}
    best: tuple[int, int] | None = None
    for beta in sympy.divisors(external_side):
        beta = int(beta)
        if (-pow(beta, -1, r)) % r not in support_residues:
            continue
        candidate = (omega(beta), beta)
        if best is None or candidate < best:
            best = candidate
    if best is None:
        raise AssertionError("support-side target state lacks a cross transporter")
    return best


def run_audit(payload: dict[str, object]) -> dict[str, object]:
    """Compare side subgroup statuses in cross hits and high-overflow misses."""
    records = []
    high_overflow_records = []
    for row in payload["records"]:
        outcome = row["zero_overflow_kind"]
        if outcome not in {"cross_essential", "none"}:
            continue
        r = int(row["r"])
        left_value, right_value = int(row["left_half_factor"]), int(row["right_half_factor"])
        left_target, left_support_size, left_group_size, left_divisor_size, left_saturated = side_supports_target(left_value, r)
        right_target, right_support_size, right_group_size, right_divisor_size, right_saturated = side_supports_target(right_value, r)
        if left_target and right_target:
            kind = "both_support_target"
        elif left_target:
            kind = "left_supports_right_external"
        elif right_target:
            kind = "left_external_right_supports"
        else:
            kind = "both_external"
        if outcome == "none":
            joint_support = generated_subgroup(
                sorted(int(q) for q in sympy.factorint(left_value))
                + sorted(int(q) for q in sympy.factorint(right_value)),
                r,
            )
            if r - 1 not in joint_support:
                raise AssertionError("high-overflow state has a joint subgroup obstruction")
            high_overflow_records.append(
                {
                    "prime": int(row["prime"]),
                    "r": r,
                    "kind": kind,
                    "joint_target_in_subgroup": True,
                }
            )
            continue
        transporter = None
        if kind == "left_supports_right_external":
            complexity, divisor = minimum_transporter_omega(int(row["left_half_factor"]), int(row["right_half_factor"]), r)
            transporter = {"direction": "right_to_left", "minimum_omega": complexity, "external_divisor": divisor}
        elif kind == "left_external_right_supports":
            complexity, divisor = minimum_transporter_omega(int(row["right_half_factor"]), int(row["left_half_factor"]), r)
            transporter = {"direction": "left_to_right", "minimum_omega": complexity, "external_divisor": divisor}
        records.append(
            {
                "prime": int(row["prime"]),
                "r": r,
                "kind": kind,
                "left_support_size": left_support_size,
                "right_support_size": right_support_size,
                "left_generated_subgroup_size": left_group_size,
                "right_generated_subgroup_size": right_group_size,
                "left_actual_divisor_residue_size": left_divisor_size,
                "right_actual_divisor_residue_size": right_divisor_size,
                "left_divisor_residues_saturate_subgroup": left_saturated,
                "right_divisor_residues_saturate_subgroup": right_saturated,
                "transporter": transporter,
            }
        )
    histogram = Counter(record["kind"] for record in records)
    target_supporting_sides = [
        (record["left_divisor_residues_saturate_subgroup"], record["kind"] in {"both_support_target", "left_supports_right_external"})
        for record in records
    ] + [
        (record["right_divisor_residues_saturate_subgroup"], record["kind"] in {"both_support_target", "left_external_right_supports"})
        for record in records
    ]
    support_side_count = sum(supports for _, supports in target_supporting_sides)
    saturated_support_side_count = sum(saturated and supports for saturated, supports in target_supporting_sides)
    transporter_histogram = Counter(
        int(record["transporter"]["minimum_omega"])
        for record in records
        if record["transporter"] is not None
    )
    high_histogram = Counter(record["kind"] for record in high_overflow_records)
    return {
        "arithmetic": (
            "exact factorization of each cross-essential half factor and closure of each side's "
            "prime residues in the unit group modulo r, tested against the target -1"
        ),
        "scope_note": (
            "A finite cross-state subgroup profile. It does not give a general cross-side transport theorem."
        ),
        "prime_limit": payload["prime_limit"],
        "cross_essential_state_count": len(records),
        "side_subgroup_kind_histogram": dict(sorted(histogram.items())),
        "one_side_supports_target_count": sum(
            record["kind"] in {"left_supports_right_external", "left_external_right_supports"}
            for record in records
        ),
        "target_supporting_side_count": support_side_count,
        "target_supporting_side_subgroup_saturated_count": saturated_support_side_count,
        "one_side_transporter_omega_histogram": {str(key): value for key, value in sorted(transporter_histogram.items())},
        "maximum_minimum_transporter_omega": max(transporter_histogram, default=None),
        "high_overflow_state_count": len(high_overflow_records),
        "high_overflow_side_subgroup_kind_histogram": dict(sorted(high_histogram.items())),
        "all_high_overflow_states_have_joint_target_in_subgroup": all(
            record["joint_target_in_subgroup"] for record in high_overflow_records
        ),
        "records": records,
        "high_overflow_records": high_overflow_records,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    result = run_audit(json.loads(args.input.read_text(encoding="utf-8")))
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {
                key: value
                for key, value in result.items()
                if key not in {"records", "high_overflow_records"}
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
