#!/usr/bin/env python3
"""Compute exact coordinate, intrinsic-box, and counterfactual boundaries for F states.

For a target fiber

    F = {z in Z^r : product(q_i**z_i) == -1 (mod R)}

and box bounds nu_i, the coordinate floor at q_j is

    delta_j = min_{z in F} max(0, abs(z_j) - nu_j).

Quotienting the support group by the subgroup generated by all q_i except q_j
makes this a one-dimensional calculation.  The script applies that exact
calculation to every support coordinate of all 253 frozen square-terminal F
states.  It also computes the intrinsic joint denominator defect

    Psi_0 = min_{z in F} sum_i max(0, abs(z_i) - nu_i)

from the original K-exponent box, together with complete minimum-cardinality
projected obstructions and signed minimum certificates.  The larger box formed
by adding current source-block heights is retained only as a counterfactual
reuse relaxation; those heights are already contained in nu.  No finite profile
here is an overflow-to-carrier injection or a universal escape theorem.
"""

from __future__ import annotations

import argparse
from collections import Counter, deque
import hashlib
import itertools
import json
import math
from pathlib import Path

import sympy
from sympy import Matrix
from sympy.matrices.normalforms import hermite_normal_form


ROOT = Path(__file__).resolve().parents[1]
ESCAPE_INPUT = (
    ROOT / "reproductions" / "type-i-private-carrier-escape-profile-results.json"
)
RELATION_INPUT = (
    ROOT
    / "reproductions"
    / "type-i-f-square-terminal-relation-certificate-results.json"
)
CAPACITY_INPUT = (
    ROOT
    / "reproductions"
    / "type-i-f-overflow-all-assignment-height-upper-bound-results.json"
)
DEFAULT_OUTPUT = (
    ROOT
    / "reproductions"
    / "type-i-private-carrier-selection-invariant-defect-results.json"
)

EXPECTED_INPUT_SHA256 = {
    ESCAPE_INPUT.name: "7466040e4f693ff39ab5d8f53e2222c18e10f3e48d1316ff8dbf767f458448df",
    RELATION_INPUT.name: "53119e9aaeadac7080811782f3a3eb07f3cd6674dfb9a18776a3c5e68d108297",
    CAPACITY_INPUT.name: "62fb9fc0f59bb011ad39276c3cd450ee1fe93fbafba7e7fc5f3800517f0bd3c5",
}
EXPECTED_ROW_COUNT = 37
EXPECTED_F_STATE_COUNT = 253
EXPECTED_SUPPORT_COORDINATE_COUNT = 1181
EXPECTED_COORDINATE_ROWS_SHA256 = (
    "4841ddcae6c8ec710355e6214bda3498c20c1da88d9ca194078ce1b0a8095781"
)
EXPECTED_SUMMARY = {
    "selection_invariant_positive_overflow_count": 0,
    "other_support_already_contains_target_count": 1173,
    "nonzero_target_class_within_box_count": 8,
    "private_proxy_positive_overflow_count": 0,
    "selection_invariant_private_overload_count": 0,
    "optimistic_extended_box_hit_count": 91,
    "optimistic_extended_box_miss_count": 162,
    "old_deterministic_no_assignment_count": 165,
    "old_deterministic_proxy_hit_by_alternative_representation_count": 3,
    "private_proxy_optimistic_box_miss_count": 37,
}
EXPECTED_POSITIVE_RESIDUAL_HISTOGRAM = {
    "1": 46,
    "2": 25,
    "3": 20,
    "4": 10,
    "5": 19,
    "6": 9,
    "7": 6,
    "8": 4,
    "9": 7,
    "10": 5,
    "11": 6,
    "12": 1,
    "13": 1,
    "14": 2,
    "15": 1,
}
EXPECTED_MINIMUM_OBSTRUCTION_DIMENSION_HISTOGRAM = {
    "2": 27,
    "3": 12,
    "4": 35,
    "5": 53,
    "6": 32,
    "7": 3,
}
EXPECTED_PRIVATE_OBSTRUCTION_DIMENSION_HISTOGRAM = {
    "2": 7,
    "3": 4,
    "4": 13,
    "5": 11,
    "6": 2,
}
EXPECTED_INTRINSIC_RESIDUAL_HISTOGRAM = {
    "1": 55,
    "2": 29,
    "3": 29,
    "4": 27,
    "5": 28,
    "6": 10,
    "7": 17,
    "8": 15,
    "9": 10,
    "10": 3,
    "11": 5,
    "12": 5,
    "13": 4,
    "14": 7,
    "15": 6,
    "18": 2,
    "19": 1,
}
EXPECTED_INTRINSIC_OBSTRUCTION_DIMENSION_HISTOGRAM = {
    "2": 42,
    "3": 23,
    "4": 65,
    "5": 67,
    "6": 49,
    "7": 7,
}
EXPECTED_PRIVATE_INTRINSIC_RESIDUAL_HISTOGRAM = {
    "3": 2,
    "4": 2,
    "5": 3,
    "6": 2,
    "7": 7,
    "8": 4,
    "9": 2,
    "11": 3,
    "12": 3,
    "13": 2,
    "14": 4,
    "15": 3,
}
EXPECTED_PRIVATE_INTRINSIC_OBSTRUCTION_DIMENSION_HISTOGRAM = {
    "2": 10,
    "3": 6,
    "4": 12,
    "5": 7,
    "6": 2,
}
EXPECTED_INTRINSIC_NONUNIQUE_OBSTRUCTION_STATES = [
    [50290249, 540755],
    [148659289, 155],
    [214360969, 267],
    [242042089, 82411],
]
EXPECTED_PRIVATE_Q_ABSENT_FROM_INTRINSIC_OBSTRUCTION_STATES = [
    [366108649, 33171, 4693697],
    [403509649, 899, 549739],
]
EXPECTED_PRIVATE_Q_OPTIONAL_IN_INTRINSIC_OBSTRUCTION_STATES = [
    [148659289, 155, 10608743],
]


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_guarded(path: Path) -> dict[str, object]:
    actual = file_sha256(path)
    if actual != EXPECTED_INPUT_SHA256[path.name]:
        raise AssertionError(f"authoritative input hash changed: {path.name}")
    return json.loads(path.read_text(encoding="utf-8"))


def exact_factorization(value: int) -> list[tuple[int, int]]:
    factors = sorted(
        (int(prime), int(exponent))
        for prime, exponent in sympy.factorint(value).items()
    )
    if math.prod(prime**exponent for prime, exponent in factors) != value:
        raise AssertionError("factorization failed to reconstruct")
    if any(not sympy.isprime(prime) for prime, _ in factors):
        raise AssertionError("factorization contains a nonprime base")
    return factors


def component_lattice_hnf(
    generator_logs: list[list[int]], component_orders: list[int]
) -> Matrix:
    dimension = len(component_orders)
    if dimension == 0:
        raise AssertionError("the unit group has no cyclic components")
    if any(len(vector) != dimension for vector in generator_logs):
        raise AssertionError("generator log vector has the wrong dimension")
    columns = [*generator_logs]
    columns.extend(
        [
            [component_orders[row] if row == column else 0 for row in range(dimension)]
            for column in range(dimension)
        ]
    )
    lattice = Matrix(
        dimension,
        len(columns),
        lambda row, column: columns[column][row],
    )
    hnf = hermite_normal_form(lattice)
    if hnf.shape != (dimension, dimension):
        raise AssertionError("HNF does not have full rank")
    return hnf


def lattice_solution(hnf: Matrix, target: list[int]) -> list[int] | None:
    dimension = len(target)
    if hnf.shape != (dimension, dimension):
        raise AssertionError("HNF membership dimension mismatch")
    if any(
        int(hnf[row, column])
        for row in range(dimension)
        for column in range(row)
    ):
        raise AssertionError("HNF is not upper triangular")
    coordinates = [0] * dimension
    for row in range(dimension - 1, -1, -1):
        diagonal = int(hnf[row, row])
        numerator = target[row] - sum(
            int(hnf[row, column]) * coordinates[column]
            for column in range(row + 1, dimension)
        )
        if diagonal <= 0 or numerator % diagonal:
            return None
        coordinates[row] = numerator // diagonal
    return coordinates


def lattice_contains(hnf: Matrix, target: list[int]) -> bool:
    return lattice_solution(hnf, target) is not None


def lattice_index(hnf: Matrix) -> int:
    return math.prod(int(hnf[index, index]) for index in range(hnf.rows))


def unit_group_logs(
    modulus: int, support_primes: list[int]
) -> tuple[list[dict[str, int]], list[list[int]], list[int]]:
    components = []
    for prime, exponent in exact_factorization(modulus):
        component_modulus = prime**exponent
        order = int(sympy.totient(component_modulus))
        root = int(sympy.primitive_root(component_modulus))
        components.append(
            {"modulus": component_modulus, "order": order, "primitive_root": root}
        )
    target = [component["order"] // 2 for component in components]
    logs = []
    for support_prime in support_primes:
        vector = [
            int(
                sympy.discrete_log(
                    component["modulus"],
                    support_prime % component["modulus"],
                    component["primitive_root"],
                )
            )
            for component in components
        ]
        for component, logarithm in zip(components, vector):
            if (
                pow(
                    component["primitive_root"],
                    logarithm,
                    component["modulus"],
                )
                != support_prime % component["modulus"]
            ):
                raise AssertionError("discrete logarithm did not reconstruct")
        logs.append(vector)
    if any(
        pow(component["primitive_root"], value, component["modulus"])
        != component["modulus"] - 1
        for component, value in zip(components, target)
    ):
        raise AssertionError("target logs do not reconstruct -1")
    return components, logs, target


def coordinate_floors(
    modulus: int, factors: list[tuple[int, int]]
) -> dict[str, object]:
    support_primes = [prime for prime, _ in factors]
    components, generator_logs, target = unit_group_logs(modulus, support_primes)
    component_orders = [component["order"] for component in components]
    full_hnf = component_lattice_hnf(generator_logs, component_orders)
    if not lattice_contains(full_hnf, target):
        raise AssertionError("an F state target left its full support subgroup")
    full_index = lattice_index(full_hnf)
    coordinate_records = []
    for selected_index, (selected_prime, bound) in enumerate(factors):
        selected_log = generator_logs[selected_index]
        other_logs = [
            vector
            for index, vector in enumerate(generator_logs)
            if index != selected_index
        ]
        other_hnf = component_lattice_hnf(other_logs, component_orders)
        other_index = lattice_index(other_hnf)
        quotient_order, remainder = divmod(other_index, full_index)
        if remainder or quotient_order < 1:
            raise AssertionError("invalid support quotient order")
        order_target = [quotient_order * value for value in selected_log]
        order_coordinates = lattice_solution(other_hnf, order_target)
        if order_coordinates is None:
            raise AssertionError(
                "selected generator does not have the certified quotient order"
            )

        target_class = None
        target_coordinates = None
        for exponent in range(quotient_order):
            difference = [
                target_value - exponent * selected_value
                for target_value, selected_value in zip(target, selected_log)
            ]
            coordinates = lattice_solution(other_hnf, difference)
            if coordinates is not None:
                target_class = exponent
                target_coordinates = coordinates
                break
        if target_class is None or target_coordinates is None:
            raise AssertionError("target has no exponent class in the cyclic quotient")
        if quotient_order > 1 and lattice_contains(
            other_hnf,
            [
                target_value - (target_class + 1) * selected_value
                for target_value, selected_value in zip(target, selected_log)
            ],
        ):
            raise AssertionError(
                "target exponent class is not unique modulo the quotient order"
            )

        signed_candidates = {target_class, target_class - quotient_order}
        minimum_signed_exponent = min(
            signed_candidates, key=lambda value: (abs(value), value)
        )
        minimum_absolute_exponent = abs(minimum_signed_exponent)
        overflow_floor = max(0, minimum_absolute_exponent - bound)
        minimum_difference = [
            target_value - minimum_signed_exponent * selected_value
            for target_value, selected_value in zip(target, selected_log)
        ]
        minimum_coordinates = lattice_solution(other_hnf, minimum_difference)
        if minimum_coordinates is None:
            raise AssertionError("minimum coordinate-floor relation failed")
        coordinate_records.append(
            {
                "support_index": selected_index,
                "support_prime": selected_prime,
                "box_exponent_bound": bound,
                "other_support_ambient_index": other_index,
                "selected_coordinate_quotient_order": quotient_order,
                "target_exponent_class": target_class,
                "minimum_signed_exponent": minimum_signed_exponent,
                "minimum_absolute_exponent": minimum_absolute_exponent,
                "selection_invariant_overflow_floor": overflow_floor,
            }
        )
    return {
        "full_support_ambient_index": full_index,
        "coordinate_floors": coordinate_records,
    }


def histogram(values: list[int]) -> dict[str, int]:
    return {str(key): count for key, count in sorted(Counter(values).items())}


def valuation(value: int, prime: int) -> int:
    exponent = 0
    while value % prime == 0:
        value //= prime
        exponent += 1
    return exponent


def certificate_rows_sha256(rows: list[dict[str, object]]) -> str:
    fields = (
        "prime",
        "R",
        "support_prime",
        "box_exponent_bound",
        "other_support_ambient_index",
        "full_support_ambient_index",
        "selected_coordinate_quotient_order",
        "target_exponent_class",
        "minimum_signed_exponent",
        "minimum_absolute_exponent",
        "selection_invariant_overflow_floor",
        "affine_projection_step",
        "affine_target_class",
    )
    payload = "".join(
        "\t".join(str(int(row[field])) for field in fields) + "\n" for row in rows
    ).encode("ascii")
    return hashlib.sha256(payload).hexdigest()


def balanced_index_split(bounds: list[int]) -> tuple[list[int], list[int]]:
    option_counts = [2 * bound + 1 for bound in bounds]
    best_key = None
    best_left: list[int] = []
    rank = len(bounds)
    for mask in range(1 << max(0, rank - 1)):
        left = [0]
        left.extend(
            index
            for index in range(1, rank)
            if mask & (1 << (index - 1))
        )
        right = [index for index in range(rank) if index not in left]
        left_count = math.prod(option_counts[index] for index in left)
        right_count = math.prod(option_counts[index] for index in right)
        key = (left_count + right_count, max(left_count, right_count), tuple(left))
        if best_key is None or key < best_key:
            best_key = key
            best_left = left
    return best_left, [index for index in range(rank) if index not in best_left]


def half_box_residues(
    modulus: int,
    factors: list[tuple[int, int]],
    bounds: list[int],
    indices: list[int],
) -> tuple[dict[int, tuple[int, ...]], int]:
    witnesses: dict[int, tuple[int, ...]] = {1 % modulus: ()}
    encoded_count = 1
    for index in indices:
        prime = factors[index][0]
        choices = list(range(-bounds[index], bounds[index] + 1))
        encoded_count *= len(choices)
        next_witnesses: dict[int, tuple[int, ...]] = {}
        powers = [(exponent, pow(prime, exponent, modulus)) for exponent in choices]
        for residue, witness in witnesses.items():
            for exponent, power in powers:
                product = residue * power % modulus
                candidate = (*witness, exponent)
                prior = next_witnesses.get(product)
                if prior is None or candidate < prior:
                    next_witnesses[product] = candidate
        witnesses = next_witnesses
    return witnesses, encoded_count


def target_box_profile(
    modulus: int,
    factors: list[tuple[int, int]],
    bounds: list[int],
) -> dict[str, object]:
    left_indices, right_indices = balanced_index_split(bounds)
    left, left_encoded = half_box_residues(
        modulus, factors, bounds, left_indices
    )
    right, right_encoded = half_box_residues(
        modulus, factors, bounds, right_indices
    )
    target = modulus - 1
    candidates = []
    for right_residue, right_witness in right.items():
        required_left = target * pow(right_residue, -1, modulus) % modulus
        if required_left not in left:
            continue
        exponents = [0] * len(factors)
        for index, exponent in zip(left_indices, left[required_left]):
            exponents[index] = exponent
        for index, exponent in zip(right_indices, right_witness):
            exponents[index] = exponent
        candidates.append(tuple(exponents))
    witness = min(candidates) if candidates else None
    if witness is not None:
        residue = math.prod(
            pow(prime, exponent, modulus)
            for (prime, _), exponent in zip(factors, witness)
        ) % modulus
        if residue != target or any(
            abs(exponent) > bound for exponent, bound in zip(witness, bounds)
        ):
            raise AssertionError("extended-box target witness failed")
    return {
        "target_in_box": witness is not None,
        "witness_exponents": list(witness) if witness is not None else None,
        "left_indices": left_indices,
        "right_indices": right_indices,
        "left_encoded_vector_count": left_encoded,
        "right_encoded_vector_count": right_encoded,
        "left_distinct_residue_count": len(left),
        "right_distinct_residue_count": len(right),
        "matching_residue_pair_count": len(candidates),
    }


def box_image_witnesses(
    modulus: int,
    factors: list[tuple[int, int]],
    bounds: list[int],
) -> dict[int, tuple[int, ...]]:
    """Return one deterministic exponent witness for each box-image residue."""
    witnesses: dict[int, tuple[int, ...]] = {1 % modulus: ()}
    for (prime, _exponent), bound in zip(factors, bounds):
        powers = [
            (value, pow(prime, value, modulus))
            for value in range(-bound, bound + 1)
        ]
        next_witnesses: dict[int, tuple[int, ...]] = {}
        for residue, witness in sorted(witnesses.items()):
            for value, power in powers:
                next_residue = residue * power % modulus
                candidate = (*witness, value)
                prior = next_witnesses.get(next_residue)
                if prior is None or candidate < prior:
                    next_witnesses[next_residue] = candidate
        witnesses = next_witnesses
    return witnesses


def exact_box_residual(
    modulus: int,
    factors: list[tuple[int, int]],
    bounds: list[int],
) -> dict[str, object]:
    """Compute min sum_i (|z_i|-bounds_i)_+ over the complete target fiber.

    This is the distance from the exponent-box image to -1 in the Cayley graph
    generated by the support primes and their inverses.  A deterministic
    shortest path supplies an exponent-vector certificate for the distance.
    """
    starts = box_image_witnesses(modulus, factors, bounds)
    target = modulus - 1
    if target in starts:
        minimum_distance = 0
        exponent_vector = list(starts[target])
        visited_residue_count = len(starts)
    else:
        generators = [
            (pow(prime, -1, modulus), index, -1)
            for index, (prime, _exponent) in enumerate(factors)
        ]
        generators.extend(
            (prime % modulus, index, 1)
            for index, (prime, _exponent) in enumerate(factors)
        )
        generators.sort(key=lambda item: (item[1], item[2], item[0]))
        distances = {residue: 0 for residue in starts}
        predecessors: dict[int, tuple[int, int, int]] = {}
        queue: deque[int] = deque(
            residue
            for residue, _witness in sorted(
                starts.items(), key=lambda item: (item[1], item[0])
            )
        )
        while queue and target not in distances:
            residue = queue.popleft()
            next_distance = distances[residue] + 1
            for generator, support_index, direction in generators:
                next_residue = residue * generator % modulus
                if next_residue in distances:
                    continue
                distances[next_residue] = next_distance
                predecessors[next_residue] = (residue, support_index, direction)
                queue.append(next_residue)
                if next_residue == target:
                    break
        if target not in distances:
            raise AssertionError("the inherited F target left the generated subgroup")
        minimum_distance = distances[target]
        extra_steps = [0] * len(factors)
        current = target
        while distances[current] > 0:
            prior, support_index, direction = predecessors[current]
            extra_steps[support_index] += direction
            current = prior
        exponent_vector = [
            value + extra
            for value, extra in zip(starts[current], extra_steps)
        ]
        visited_residue_count = len(distances)

    negative_excess = [
        max(0, -value - bound)
        for value, bound in zip(exponent_vector, bounds)
    ]
    positive_excess = [
        max(0, value - bound)
        for value, bound in zip(exponent_vector, bounds)
    ]
    reconstructed = math.prod(
        pow(prime, value, modulus)
        for (prime, _exponent), value in zip(factors, exponent_vector)
    ) % modulus
    if reconstructed != target:
        raise AssertionError("minimum residual certificate missed the target")
    if sum(negative_excess) + sum(positive_excess) != minimum_distance:
        raise AssertionError("minimum residual certificate has the wrong distance")
    return {
        "minimum_unit_residual": minimum_distance,
        "box_image_size": len(starts),
        "visited_residue_count": visited_residue_count,
        "canonical_minimum_certificate": {
            "exponent_vector": exponent_vector,
            "negative_excess": negative_excess,
            "positive_excess": positive_excess,
        },
    }


def signed_intrinsic_pareto_certificates(
    modulus: int,
    factors: list[tuple[int, int]],
    intrinsic_profile: dict[str, object],
) -> list[dict[str, object]]:
    """Return canonical and sign-reflected signed Pareto certificates.

    Every returned point has globally minimum L1 defect Psi_0, hence no signed
    defect vector can strictly dominate it.  This certifies Pareto points but
    does not enumerate the complete signed Pareto frontier.
    """
    bounds = [exponent for _prime, exponent in factors]
    canonical = intrinsic_profile["canonical_minimum_certificate"]
    exponent_vector = [int(value) for value in canonical["exponent_vector"]]
    minimum_distance = int(intrinsic_profile["minimum_unit_residual"])
    records = []
    seen = set()
    for label, vector in (
        ("canonical", exponent_vector),
        ("sign_reflection", [-value for value in exponent_vector]),
    ):
        d_minus = [
            max(0, -value - bound) for value, bound in zip(vector, bounds)
        ]
        d_plus = [
            max(0, value - bound) for value, bound in zip(vector, bounds)
        ]
        key = (*d_minus, *d_plus)
        if key in seen:
            continue
        seen.add(key)
        if sum(d_minus) + sum(d_plus) != minimum_distance:
            raise AssertionError("signed certificate does not realize Psi_0")
        residue = math.prod(
            pow(prime, value, modulus)
            for (prime, _exponent), value in zip(factors, vector)
        ) % modulus
        if residue != modulus - 1:
            raise AssertionError("signed certificate left the target fiber")
        records.append(
            {
                "relation": label,
                "exponent_vector": vector,
                "d_minus": d_minus,
                "d_plus": d_plus,
                "X_minus_factorization": [
                    [prime, defect]
                    for (prime, _exponent), defect in zip(factors, d_minus)
                    if defect
                ],
                "X_plus_factorization": [
                    [prime, defect]
                    for (prime, _exponent), defect in zip(factors, d_plus)
                    if defect
                ],
                "total_signed_defect": minimum_distance,
                "pareto_minimal_by_global_l1_minimum": True,
            }
        )
    return records


def minimum_projected_box_obstructions(
    target_preimage: list[int],
    relation_columns: list[list[int]],
    bounds: list[int],
) -> dict[str, object]:
    """Find the smallest coordinate sets whose projected affine fiber misses its box."""
    rank = len(bounds)
    for dimension in range(1, rank + 1):
        obstructions: list[list[int]] = []
        for indices_tuple in itertools.combinations(range(rank), dimension):
            indices = list(indices_tuple)
            projected = Matrix(
                dimension,
                rank,
                lambda row, column: relation_columns[column][indices[row]],
            )
            projected_hnf = hermite_normal_form(projected)
            if projected_hnf.shape != (dimension, dimension):
                raise AssertionError("a relation-lattice projection lost full rank")
            intersects = False
            choices = [range(-bounds[index], bounds[index] + 1) for index in indices]
            for candidate in itertools.product(*choices):
                difference = [
                    value - target_preimage[index]
                    for value, index in zip(candidate, indices)
                ]
                if lattice_contains(projected_hnf, difference):
                    intersects = True
                    break
            if not intersects:
                obstructions.append(indices)
        if obstructions:
            return {
                "minimum_dimension": dimension,
                "support_index_sets": obstructions,
                "unique": len(obstructions) == 1,
            }
    raise AssertionError("the full projected affine fiber unexpectedly met the box")


def run_audit() -> dict[str, object]:
    escape = load_guarded(ESCAPE_INPUT)
    relation = load_guarded(RELATION_INPUT)
    capacity = load_guarded(CAPACITY_INPUT)
    if len(relation["records"]) != EXPECTED_F_STATE_COUNT:
        raise AssertionError("frozen F-state count changed")
    private_by_coordinate = {
        (int(record["prime"]), int(record["R"]), int(record["q"])): record
        for record in escape["records"]
    }
    if len(private_by_coordinate) != EXPECTED_ROW_COUNT:
        raise AssertionError("private state count changed")
    capacity_by_state = {
        (int(record["prime"]), int(record["R"])): record
        for record in capacity["records"]
    }
    if len(capacity_by_state) != EXPECTED_F_STATE_COUNT:
        raise AssertionError("capacity state count changed")
    private_state_keys = {
        (prime, modulus) for prime, modulus, _q in private_by_coordinate
    }

    state_records = []
    private_records = []
    all_coordinate_records = []
    for state in relation["records"]:
        prime = int(state["prime"])
        modulus = int(state["R"])
        K = int(state["K"])
        factors = [(int(q), int(exponent)) for q, exponent in state["factorization"]]
        if math.prod(q**exponent for q, exponent in factors) != K:
            raise AssertionError("stored K factorization did not reconstruct")
        if K % 2 == 0 or any(q == 2 for q, _exponent in factors):
            raise AssertionError("the frozen square-terminal K support ceased to be odd")
        a = int(state["a"])
        s = int(state["s"])
        if prime != a + s + a * s * modulus:
            raise AssertionError("stored linear source did not reconstruct")
        blocks = [a * modulus + 1, s * modulus + 1]
        if blocks[0] * blocks[1] != 4 * K or prime * modulus + 1 != 4 * K:
            raise AssertionError("current source blocks do not multiply to 4K")
        source_block_heights = [
            [valuation(block, q) for q, _exponent in factors]
            for block in blocks
        ]
        if any(
            source_block_heights[0][index] + source_block_heights[1][index]
            != exponent
            for index, (_q, exponent) in enumerate(factors)
        ):
            raise AssertionError("current source blocks do not saturate a K exponent")
        carrier_heights = [
            max(valuation(block, q) for block in blocks) for q, _ in factors
        ]
        extended_bounds = [
            exponent + height
            for (_q, exponent), height in zip(factors, carrier_heights)
        ]
        extended_box = target_box_profile(modulus, factors, extended_bounds)
        optimistic_residual = exact_box_residual(
            modulus, factors, extended_bounds
        )
        if bool(extended_box["target_in_box"]) != (
            int(optimistic_residual["minimum_unit_residual"]) == 0
        ):
            raise AssertionError("MITM box membership and Cayley distance disagree")
        extended_witness = extended_box["witness_exponents"]
        if extended_witness is not None:
            witness_overflow = [
                max(0, abs(int(value)) - exponent)
                for value, (_q, exponent) in zip(extended_witness, factors)
            ]
            if any(
                excess > height
                for excess, height in zip(witness_overflow, carrier_heights)
            ):
                raise AssertionError("extended-box witness exceeds a carrier height")
        else:
            witness_overflow = None
        old_capacity = capacity_by_state[(prime, modulus)]
        if int(old_capacity["admissible_assignment_count"]) != 2:
            raise AssertionError("the frozen source no longer has two orientations")
        stored_heights = {
            int(q): int(height)
            for q, height in old_capacity["max_height_by_q"].items()
        }
        computed_heights = {
            q: height for (q, _exponent), height in zip(factors, carrier_heights)
        }
        if any(
            q not in computed_heights or computed_heights[q] != height
            for q, height in stored_heights.items()
        ):
            raise AssertionError(
                "extended-box heights disagree with the capacity input at "
                f"(p,R)=({prime},{modulus}): stored={stored_heights}, "
                f"computed={computed_heights}"
            )
        old_no_assignment = (
            old_capacity["category"] == "no_assignment_can_carry_all_excess"
        )
        if not extended_box["target_in_box"] and not old_no_assignment:
            raise AssertionError(
                "an exact optimistic-box miss escaped the old no-assignment class"
            )
        floor_certificate = coordinate_floors(modulus, factors)
        target_preimage = [int(value) for value in state["target_preimage"]]
        relation_columns = [
            [int(value) for value in column]
            for column in state["relation_basis_columns"]
        ]
        if (
            len(target_preimage) != len(factors)
            or len(relation_columns) != len(factors)
            or any(len(column) != len(factors) for column in relation_columns)
        ):
            raise AssertionError("stored affine relation lattice has the wrong rank")
        intrinsic_bounds = [exponent for _q, exponent in factors]
        intrinsic_residual = exact_box_residual(
            modulus, factors, intrinsic_bounds
        )
        if int(intrinsic_residual["minimum_unit_residual"]) <= 0:
            raise AssertionError("an intrinsic original exponent box met the target")
        intrinsic_obstruction = minimum_projected_box_obstructions(
            target_preimage, relation_columns, intrinsic_bounds
        )
        intrinsic_obstruction["support_prime_sets"] = [
            [factors[index][0] for index in indices]
            for indices in intrinsic_obstruction["support_index_sets"]
        ]
        signed_certificates = signed_intrinsic_pareto_certificates(
            modulus, factors, intrinsic_residual
        )
        if len(signed_certificates) != 2:
            raise AssertionError("positive intrinsic defect lost its sign-reflected pair")
        if extended_witness is None:
            minimum_obstruction = minimum_projected_box_obstructions(
                target_preimage, relation_columns, extended_bounds
            )
            minimum_obstruction["support_prime_sets"] = [
                [factors[index][0] for index in indices]
                for indices in minimum_obstruction["support_index_sets"]
            ]
        else:
            minimum_obstruction = None
        enriched_coordinates = []
        for coordinate in floor_certificate["coordinate_floors"]:
            selected_prime = int(coordinate["support_prime"])
            selected_index = int(coordinate["support_index"])
            invariant_floor = int(coordinate["selection_invariant_overflow_floor"])
            projection_step = math.gcd(
                *(abs(column[selected_index]) for column in relation_columns)
            )
            if projection_step < 1:
                raise AssertionError("affine coordinate projection has zero step")
            affine_target_class = target_preimage[selected_index] % projection_step
            affine_minimum_absolute = min(
                affine_target_class, projection_step - affine_target_class
            )
            affine_floor = max(
                0,
                affine_minimum_absolute - int(coordinate["box_exponent_bound"]),
            )
            if (
                projection_step
                != int(coordinate["selected_coordinate_quotient_order"])
                or affine_target_class != int(coordinate["target_exponent_class"])
                or affine_minimum_absolute
                != int(coordinate["minimum_absolute_exponent"])
                or affine_floor != invariant_floor
            ):
                raise AssertionError(
                    "affine projection and support quotient disagree on a coordinate floor"
                )
            enriched = {
                **coordinate,
                "affine_projection_step": projection_step,
                "affine_target_class": affine_target_class,
            }
            key = (prime, modulus, selected_prime)
            if key in private_by_coordinate:
                private = private_by_coordinate[key]
                proxy_excess = int(private["overflow_excess"])
                carrier_height = int(private["block_height"])
                if invariant_floor > proxy_excess:
                    raise AssertionError(
                        "a coordinate floor exceeds an observed target witness"
                    )
                if "smaller_R_witness" in private:
                    alternative = private["smaller_R_witness"]
                    alternative_relation = "smaller_R"
                else:
                    alternative = private["first_larger_R_hit"]
                    alternative_relation = "larger_R"
                alternative_R = int(alternative["R"])
                alternative_K = int(alternative["K"])
                if (
                    alternative_R == modulus
                    or alternative_K % selected_prime == 0
                    or 4 * alternative_K != prime * alternative_R + 1
                ):
                    raise AssertionError(
                        "alternative Type I hit did not renew the private support"
                    )
                private_payload = {
                    "prime": prime,
                    "R": modulus,
                    "K": K,
                    "private_q": selected_prime,
                    "private_block_height": carrier_height,
                    "deterministic_proxy_excess": proxy_excess,
                    "selected_coordinate_quotient_order": int(
                        enriched["selected_coordinate_quotient_order"]
                    ),
                    "target_exponent_class": int(enriched["target_exponent_class"]),
                    "minimum_signed_exponent": int(
                        enriched["minimum_signed_exponent"]
                    ),
                    "selection_invariant_overflow_floor": invariant_floor,
                    "selection_invariant_private_overload": (
                        invariant_floor > carrier_height
                    ),
                    "proxy_minus_invariant_floor": proxy_excess - invariant_floor,
                    "alternative_q_free_type_I": {
                        "relative_R": alternative_relation,
                        "R": alternative_R,
                        "K": alternative_K,
                        "q_absent_from_K": alternative_K % selected_prime != 0,
                    },
                }
                private_records.append(private_payload)
            enriched_coordinates.append(enriched)
            all_coordinate_records.append(
                {
                    "prime": prime,
                    "R": modulus,
                    "full_support_ambient_index": int(
                        floor_certificate["full_support_ambient_index"]
                    ),
                    **enriched,
                }
            )
        state_records.append(
            {
                "prime": prime,
                "R": modulus,
                "K": K,
                "factorization": [[q, exponent] for q, exponent in factors],
                "source": {"a": a, "s": s},
                "source_block_q_heights": source_block_heights,
                "current_block_saturation_verified": True,
                "intrinsic_original_exponent_box": {
                    "bounds": intrinsic_bounds,
                    "target_in_box": False,
                    **intrinsic_residual,
                    "signed_minimum_l1_pareto_certificates": signed_certificates,
                    "signed_pareto_scope": (
                        "The canonical minimum-L1 point and its sign reflection are "
                        "certified Pareto points; this is not a complete Pareto-frontier "
                        "enumeration."
                    ),
                    "minimum_projected_obstruction": intrinsic_obstruction,
                },
                "carrier_height_upper_bound": carrier_heights,
                "extended_box_bounds": extended_bounds,
                "optimistic_rectangular_extended_box": {
                    "counterfactual_current_block_reuse": True,
                    "target_in_box": bool(extended_box["target_in_box"]),
                    "witness_exponents": extended_witness,
                    "witness_overflow": witness_overflow,
                    "old_deterministic_no_assignment": old_no_assignment,
                    **optimistic_residual,
                    "minimum_projected_obstruction": minimum_obstruction,
                    "half_box_encoded_vector_counts": [
                        int(extended_box["left_encoded_vector_count"]),
                        int(extended_box["right_encoded_vector_count"]),
                    ],
                    "half_box_distinct_residue_counts": [
                        int(extended_box["left_distinct_residue_count"]),
                        int(extended_box["right_distinct_residue_count"]),
                    ],
                },
                "full_support_ambient_index": int(
                    floor_certificate["full_support_ambient_index"]
                ),
                "coordinate_floors": enriched_coordinates,
            }
        )

    if len(private_records) != EXPECTED_ROW_COUNT:
        raise AssertionError("not every private proxy coordinate was recovered")
    floors = [
        int(record["selection_invariant_overflow_floor"])
        for record in all_coordinate_records
    ]
    quotient_orders = [
        int(record["selected_coordinate_quotient_order"])
        for record in all_coordinate_records
    ]
    target_classes = [int(record["target_exponent_class"]) for record in all_coordinate_records]
    positive = [
        record
        for record in all_coordinate_records
        if int(record["selection_invariant_overflow_floor"]) > 0
    ]
    private_overloaded = [
        record
        for record in private_records
        if record["selection_invariant_private_overload"]
    ]
    optimistic_box_misses = [
        record
        for record in state_records
        if not record["optimistic_rectangular_extended_box"]["target_in_box"]
    ]
    optimistic_box_hits = [
        record
        for record in state_records
        if record["optimistic_rectangular_extended_box"]["target_in_box"]
    ]
    old_no_assignment_records = [
        record
        for record in state_records
        if record["optimistic_rectangular_extended_box"][
            "old_deterministic_no_assignment"
        ]
    ]
    old_proxy_alternative_hits = [
        record
        for record in old_no_assignment_records
        if record["optimistic_rectangular_extended_box"]["target_in_box"]
    ]
    private_optimistic_box_misses = [
        record
        for record in state_records
        if (int(record["prime"]), int(record["R"])) in private_state_keys
        and not record["optimistic_rectangular_extended_box"]["target_in_box"]
    ]
    residuals = [
        int(record["optimistic_rectangular_extended_box"]["minimum_unit_residual"])
        for record in state_records
    ]
    positive_residuals = [value for value in residuals if value > 0]
    intrinsic_residuals = [
        int(record["intrinsic_original_exponent_box"]["minimum_unit_residual"])
        for record in state_records
    ]
    if any(value <= 0 for value in intrinsic_residuals):
        raise AssertionError("not every frozen F state has positive intrinsic defect")
    if any(
        intrinsic < counterfactual
        for intrinsic, counterfactual in zip(intrinsic_residuals, residuals)
    ):
        raise AssertionError("enlarging an exponent box increased its minimum residual")
    intrinsic_obstruction_dimensions = [
        int(
            record["intrinsic_original_exponent_box"][
                "minimum_projected_obstruction"
            ]["minimum_dimension"]
        )
        for record in state_records
    ]
    intrinsic_unique_obstruction_count = sum(
        bool(
            record["intrinsic_original_exponent_box"][
                "minimum_projected_obstruction"
            ]["unique"]
        )
        for record in state_records
    )
    intrinsic_nonunique_obstruction_states = sorted(
        [int(record["prime"]), int(record["R"])]
        for record in state_records
        if not record["intrinsic_original_exponent_box"][
            "minimum_projected_obstruction"
        ]["unique"]
    )
    obstruction_dimensions = [
        int(
            record["optimistic_rectangular_extended_box"][
                "minimum_projected_obstruction"
            ]["minimum_dimension"]
        )
        for record in optimistic_box_misses
    ]
    unique_obstruction_count = sum(
        bool(
            record["optimistic_rectangular_extended_box"][
                "minimum_projected_obstruction"
            ]["unique"]
        )
        for record in optimistic_box_misses
    )
    private_q_by_state = {
        (int(record["prime"]), int(record["R"])): int(record["private_q"])
        for record in private_records
    }
    private_obstruction_dimensions = []
    private_obstruction_contains_q_count = 0
    for record in private_optimistic_box_misses:
        key = (int(record["prime"]), int(record["R"]))
        obstruction = record["optimistic_rectangular_extended_box"][
            "minimum_projected_obstruction"
        ]
        private_obstruction_dimensions.append(int(obstruction["minimum_dimension"]))
        private_q = private_q_by_state[key]
        if any(
            private_q in support_set
            for support_set in obstruction["support_prime_sets"]
        ):
            private_obstruction_contains_q_count += 1
    private_intrinsic_records = [
        record
        for record in state_records
        if (int(record["prime"]), int(record["R"])) in private_state_keys
    ]
    private_intrinsic_residuals = [
        int(record["intrinsic_original_exponent_box"]["minimum_unit_residual"])
        for record in private_intrinsic_records
    ]
    private_intrinsic_obstruction_dimensions = [
        int(
            record["intrinsic_original_exponent_box"][
                "minimum_projected_obstruction"
            ]["minimum_dimension"]
        )
        for record in private_intrinsic_records
    ]
    private_intrinsic_unique_obstruction_count = sum(
        bool(
            record["intrinsic_original_exponent_box"][
                "minimum_projected_obstruction"
            ]["unique"]
        )
        for record in private_intrinsic_records
    )
    private_q_in_some_intrinsic_obstruction_count = 0
    private_q_in_every_intrinsic_obstruction_count = 0
    private_q_absent_intrinsic_obstruction_states = []
    private_q_optional_intrinsic_obstruction_states = []
    for record in private_intrinsic_records:
        key = (int(record["prime"]), int(record["R"]))
        private_q = private_q_by_state[key]
        prime_sets = record["intrinsic_original_exponent_box"][
            "minimum_projected_obstruction"
        ]["support_prime_sets"]
        membership = [private_q in support_set for support_set in prime_sets]
        if any(membership):
            private_q_in_some_intrinsic_obstruction_count += 1
        else:
            private_q_absent_intrinsic_obstruction_states.append(
                [*key, private_q]
            )
        if all(membership):
            private_q_in_every_intrinsic_obstruction_count += 1
        elif any(membership):
            private_q_optional_intrinsic_obstruction_states.append(
                [*key, private_q]
            )
    private_q_absent_intrinsic_obstruction_states.sort()
    private_q_optional_intrinsic_obstruction_states.sort()
    sorted_intrinsic_residuals = sorted(intrinsic_residuals)
    sorted_private_intrinsic_residuals = sorted(private_intrinsic_residuals)
    result = {
        "arithmetic": (
            "For every K-support coordinate of every frozen square-terminal F state, "
            "quotient the support group modulo R by the subgroup generated by all other "
            "support primes. The cyclic quotient target class gives the exact minimum "
            "absolute exponent and coordinatewise overflow floor over the full target fiber. "
            "The original exponent box distance Psi_0 is computed independently as a "
            "multi-source Cayley-graph distance to -1."
        ),
        "scope_note": (
            "The coordinate floor is selection-invariant over the complete target fiber, "
            "but it is only a coordinatewise necessity. It does not prove a carrier charge, "
            "a compatible carrier flow, an overflow-to-carrier injection, or a "
            "universal Type I/II escape theorem. The intrinsic profile uses exactly the "
            "K-exponent bounds nu. The extended box adds current source-block heights "
            "that are already saturated inside nu, so it is retained only as a "
            "counterfactual one-reuse rectangular relaxation, not a compatible capacity."
        ),
        "inputs": {
            path.name: {"sha256": EXPECTED_INPUT_SHA256[path.name]}
            for path in (ESCAPE_INPUT, RELATION_INPUT, CAPACITY_INPUT)
        },
        "F_state_count": len(state_records),
        "support_coordinate_count": len(all_coordinate_records),
        "coordinate_certificate_rows_sha256": certificate_rows_sha256(
            all_coordinate_records
        ),
        "selection_invariant_positive_overflow_count": len(positive),
        "other_support_already_contains_target_count": sum(
            target_class == 0 for target_class in target_classes
        ),
        "nonzero_target_class_within_box_count": sum(
            int(record["target_exponent_class"]) != 0
            and int(record["selection_invariant_overflow_floor"]) == 0
            for record in all_coordinate_records
        ),
        "selection_invariant_overflow_floor_histogram": histogram(floors),
        "selected_coordinate_quotient_order_histogram": histogram(quotient_orders),
        "private_proxy_coordinate_count": len(private_records),
        "private_proxy_positive_overflow_count": sum(
            int(record["selection_invariant_overflow_floor"]) > 0
            for record in private_records
        ),
        "selection_invariant_private_overload_count": len(private_overloaded),
        "alternative_q_free_type_I_count": sum(
            bool(record["alternative_q_free_type_I"]["q_absent_from_K"])
            for record in private_records
        ),
        "alternative_R_relation_histogram": histogram(
            [
                -1
                if record["alternative_q_free_type_I"]["relative_R"] == "smaller_R"
                else 1
                for record in private_records
            ]
        ),
        "intrinsic_original_box_hit_count": sum(
            value == 0 for value in intrinsic_residuals
        ),
        "intrinsic_original_box_miss_count": sum(
            value > 0 for value in intrinsic_residuals
        ),
        "intrinsic_unit_residual_histogram": histogram(intrinsic_residuals),
        "intrinsic_unit_residual_sum": sum(intrinsic_residuals),
        "intrinsic_unit_residual_mean": {
            "numerator": sum(intrinsic_residuals),
            "denominator": len(intrinsic_residuals),
            "decimal": f"{sum(intrinsic_residuals) / len(intrinsic_residuals):.10f}",
        },
        "intrinsic_unit_residual_median": sorted_intrinsic_residuals[
            len(sorted_intrinsic_residuals) // 2
        ],
        "maximum_intrinsic_unit_residual": max(intrinsic_residuals),
        "maximum_intrinsic_unit_residual_states": [
            [int(record["prime"]), int(record["R"]), int(record["K"])]
            for record in state_records
            if int(
                record["intrinsic_original_exponent_box"]["minimum_unit_residual"]
            )
            == max(intrinsic_residuals)
        ],
        "intrinsic_minimum_projected_obstruction_dimension_histogram": histogram(
            intrinsic_obstruction_dimensions
        ),
        "intrinsic_unique_minimum_projected_obstruction_count": (
            intrinsic_unique_obstruction_count
        ),
        "intrinsic_nonunique_minimum_projected_obstruction_states": (
            intrinsic_nonunique_obstruction_states
        ),
        "private_proxy_intrinsic_unit_residual_histogram": histogram(
            private_intrinsic_residuals
        ),
        "private_proxy_intrinsic_unit_residual_sum": sum(
            private_intrinsic_residuals
        ),
        "private_proxy_intrinsic_unit_residual_mean": {
            "numerator": sum(private_intrinsic_residuals),
            "denominator": len(private_intrinsic_residuals),
            "decimal": (
                f"{sum(private_intrinsic_residuals) / len(private_intrinsic_residuals):.10f}"
            ),
        },
        "private_proxy_intrinsic_unit_residual_median": (
            sorted_private_intrinsic_residuals[
                len(sorted_private_intrinsic_residuals) // 2
            ]
        ),
        "private_proxy_intrinsic_unit_residual_range": [
            min(private_intrinsic_residuals),
            max(private_intrinsic_residuals),
        ],
        "private_proxy_intrinsic_minimum_obstruction_dimension_histogram": histogram(
            private_intrinsic_obstruction_dimensions
        ),
        "private_proxy_intrinsic_unique_minimum_obstruction_count": (
            private_intrinsic_unique_obstruction_count
        ),
        "private_proxy_intrinsic_minimum_obstruction_contains_private_q_in_some_count": (
            private_q_in_some_intrinsic_obstruction_count
        ),
        "private_proxy_intrinsic_minimum_obstruction_contains_private_q_in_every_count": (
            private_q_in_every_intrinsic_obstruction_count
        ),
        "private_proxy_intrinsic_minimum_obstruction_absent_private_q_states": (
            private_q_absent_intrinsic_obstruction_states
        ),
        "private_proxy_intrinsic_minimum_obstruction_optional_private_q_states": (
            private_q_optional_intrinsic_obstruction_states
        ),
        "counterfactual_reuse_minimum_residual_sum": sum(residuals),
        "intrinsic_minus_counterfactual_minimum_residual_sum": (
            sum(intrinsic_residuals) - sum(residuals)
        ),
        "counterfactual_hit_but_intrinsic_miss_count": sum(
            intrinsic > 0 and counterfactual == 0
            for intrinsic, counterfactual in zip(intrinsic_residuals, residuals)
        ),
        "optimistic_extended_box_hit_count": len(optimistic_box_hits),
        "optimistic_extended_box_miss_count": len(optimistic_box_misses),
        "optimistic_unit_residual_histogram": histogram(residuals),
        "positive_optimistic_unit_residual_histogram": histogram(positive_residuals),
        "maximum_optimistic_unit_residual": max(residuals),
        "maximum_optimistic_unit_residual_states": [
            [int(record["prime"]), int(record["R"])]
            for record in state_records
            if int(
                record["optimistic_rectangular_extended_box"][
                    "minimum_unit_residual"
                ]
            )
            == max(residuals)
        ],
        "minimum_projected_obstruction_dimension_histogram": histogram(
            obstruction_dimensions
        ),
        "unique_minimum_projected_obstruction_count": unique_obstruction_count,
        "private_proxy_minimum_obstruction_dimension_histogram": histogram(
            private_obstruction_dimensions
        ),
        "private_proxy_minimum_obstruction_contains_private_q_count": (
            private_obstruction_contains_q_count
        ),
        "old_deterministic_no_assignment_count": len(old_no_assignment_records),
        "old_deterministic_proxy_hit_by_alternative_representation_count": len(
            old_proxy_alternative_hits
        ),
        "old_deterministic_proxy_hit_by_alternative_representation_states": [
            [int(record["prime"]), int(record["R"])]
            for record in old_proxy_alternative_hits
        ],
        "private_proxy_optimistic_box_miss_count": len(
            private_optimistic_box_misses
        ),
        "positive_overflow_states": [
            [
                int(record["prime"]),
                int(record["R"]),
                int(record["support_prime"]),
                int(record["selection_invariant_overflow_floor"]),
            ]
            for record in positive
        ],
        "private_overload_states": [
            [
                int(record["prime"]),
                int(record["R"]),
                int(record["private_q"]),
                int(record["selection_invariant_overflow_floor"]),
                int(record["private_block_height"]),
            ]
            for record in private_overloaded
        ],
        "private_proxy_records": private_records,
        "records": state_records,
    }
    if result["support_coordinate_count"] != EXPECTED_SUPPORT_COORDINATE_COUNT:
        raise AssertionError("frozen support-coordinate count changed")
    if result["coordinate_certificate_rows_sha256"] != EXPECTED_COORDINATE_ROWS_SHA256:
        raise AssertionError("coordinate certificate rows changed")
    for field, expected in EXPECTED_SUMMARY.items():
        if result[field] != expected:
            raise AssertionError(
                f"frozen summary changed at {field}: {result[field]} != {expected}"
            )
    if result[
        "old_deterministic_proxy_hit_by_alternative_representation_states"
    ] != [
        [79312489, 1571],
        [214360969, 11171],
        [549401449, 6787],
    ]:
        raise AssertionError("the repaired deterministic-proxy states changed")
    if (
        result["positive_optimistic_unit_residual_histogram"]
        != EXPECTED_POSITIVE_RESIDUAL_HISTOGRAM
    ):
        raise AssertionError("the positive optimistic residual histogram changed")
    if result["maximum_optimistic_unit_residual_states"] != [
        [310002289, 137595]
    ]:
        raise AssertionError("the maximum optimistic residual state changed")
    if (
        result["minimum_projected_obstruction_dimension_histogram"]
        != EXPECTED_MINIMUM_OBSTRUCTION_DIMENSION_HISTOGRAM
    ):
        raise AssertionError("the minimum obstruction dimension histogram changed")
    if result["unique_minimum_projected_obstruction_count"] != 162:
        raise AssertionError("a minimum projected obstruction ceased to be unique")
    if (
        result["private_proxy_minimum_obstruction_dimension_histogram"]
        != EXPECTED_PRIVATE_OBSTRUCTION_DIMENSION_HISTOGRAM
    ):
        raise AssertionError("the private obstruction dimension histogram changed")
    if result["private_proxy_minimum_obstruction_contains_private_q_count"] != 37:
        raise AssertionError("a private q left its minimum projected obstruction")
    if result["intrinsic_original_box_hit_count"] != 0:
        raise AssertionError("an original exponent box met the target")
    if result["intrinsic_original_box_miss_count"] != EXPECTED_F_STATE_COUNT:
        raise AssertionError("not every original exponent box misses the target")
    if result["intrinsic_unit_residual_histogram"] != EXPECTED_INTRINSIC_RESIDUAL_HISTOGRAM:
        raise AssertionError("the intrinsic residual histogram changed")
    if result["intrinsic_unit_residual_sum"] != 1277:
        raise AssertionError("the intrinsic residual sum changed")
    if result["intrinsic_unit_residual_mean"] != {
        "numerator": 1277,
        "denominator": 253,
        "decimal": "5.0474308300",
    }:
        raise AssertionError("the intrinsic residual mean changed")
    if result["intrinsic_unit_residual_median"] != 4:
        raise AssertionError("the intrinsic residual median changed")
    if result["maximum_intrinsic_unit_residual"] != 19:
        raise AssertionError("the maximum intrinsic residual changed")
    if result["maximum_intrinsic_unit_residual_states"] != [
        [310002289, 137595, 10663691238739]
    ]:
        raise AssertionError("the maximum intrinsic residual state changed")
    if (
        result["intrinsic_minimum_projected_obstruction_dimension_histogram"]
        != EXPECTED_INTRINSIC_OBSTRUCTION_DIMENSION_HISTOGRAM
    ):
        raise AssertionError("the intrinsic obstruction dimension histogram changed")
    if result["intrinsic_unique_minimum_projected_obstruction_count"] != 249:
        raise AssertionError("the intrinsic unique-obstruction count changed")
    if (
        result["intrinsic_nonunique_minimum_projected_obstruction_states"]
        != EXPECTED_INTRINSIC_NONUNIQUE_OBSTRUCTION_STATES
    ):
        raise AssertionError("the intrinsic tied-obstruction states changed")
    if (
        result["private_proxy_intrinsic_unit_residual_histogram"]
        != EXPECTED_PRIVATE_INTRINSIC_RESIDUAL_HISTOGRAM
    ):
        raise AssertionError("the private intrinsic residual histogram changed")
    if result["private_proxy_intrinsic_unit_residual_sum"] != 336:
        raise AssertionError("the private intrinsic residual sum changed")
    if result["private_proxy_intrinsic_unit_residual_mean"] != {
        "numerator": 336,
        "denominator": 37,
        "decimal": "9.0810810811",
    }:
        raise AssertionError("the private intrinsic residual mean changed")
    if result["private_proxy_intrinsic_unit_residual_median"] != 8:
        raise AssertionError("the private intrinsic residual median changed")
    if result["private_proxy_intrinsic_unit_residual_range"] != [3, 15]:
        raise AssertionError("the private intrinsic residual range changed")
    if (
        result["private_proxy_intrinsic_minimum_obstruction_dimension_histogram"]
        != EXPECTED_PRIVATE_INTRINSIC_OBSTRUCTION_DIMENSION_HISTOGRAM
    ):
        raise AssertionError("the private intrinsic obstruction histogram changed")
    if result["private_proxy_intrinsic_unique_minimum_obstruction_count"] != 36:
        raise AssertionError("the private intrinsic unique-obstruction count changed")
    if (
        result[
            "private_proxy_intrinsic_minimum_obstruction_contains_private_q_in_some_count"
        ]
        != 35
    ):
        raise AssertionError("the private-q some-obstruction count changed")
    if (
        result[
            "private_proxy_intrinsic_minimum_obstruction_contains_private_q_in_every_count"
        ]
        != 34
    ):
        raise AssertionError("the private-q every-obstruction count changed")
    if (
        result[
            "private_proxy_intrinsic_minimum_obstruction_absent_private_q_states"
        ]
        != EXPECTED_PRIVATE_Q_ABSENT_FROM_INTRINSIC_OBSTRUCTION_STATES
    ):
        raise AssertionError("the states intrinsically avoiding private q changed")
    if (
        result[
            "private_proxy_intrinsic_minimum_obstruction_optional_private_q_states"
        ]
        != EXPECTED_PRIVATE_Q_OPTIONAL_IN_INTRINSIC_OBSTRUCTION_STATES
    ):
        raise AssertionError("the state with optional private q changed")
    if result["counterfactual_reuse_minimum_residual_sum"] != 666:
        raise AssertionError("the counterfactual minimum-residual sum changed")
    if result["intrinsic_minus_counterfactual_minimum_residual_sum"] != 611:
        raise AssertionError("the intrinsic/counterfactual residual gap changed")
    if result["counterfactual_hit_but_intrinsic_miss_count"] != 91:
        raise AssertionError("the counterfactual-only hit count changed")
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    result = run_audit()
    args.output.write_text(
        json.dumps(result, indent=2, ensure_ascii=True) + "\n", encoding="utf-8"
    )
    print(
        "F states={F_state_count}, coordinates={support_coordinate_count}, "
        "positive coordinate floors={selection_invariant_positive_overflow_count}, "
        "intrinsic misses={intrinsic_original_box_miss_count}, "
        "max intrinsic residual={maximum_intrinsic_unit_residual}, "
        "optimistic box misses={optimistic_extended_box_miss_count}, "
        "max residual={maximum_optimistic_unit_residual}, alternative proxy hits="
        "{old_deterministic_proxy_hit_by_alternative_representation_count}".format(
            **result
        )
    )


if __name__ == "__main__":
    main()
