#!/usr/bin/env python3
"""Measure prime-repeat steps needed to reach the zero-overflow divisor target."""

from __future__ import annotations

import argparse
from collections import Counter
import heapq
import json
from pathlib import Path

import sympy


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "reproductions" / "type-ii-h19-bounded-r-overflow-profile-1b-results.json"
DEFAULT_OUTPUT = ROOT / "reproductions" / "type-ii-h19-zero-overflow-exponent-deficit-1b-results.json"


def support_word_distances(primes: list[int], modulus: int) -> dict[int, int]:
    """Shortest word length for every generated residue using repeated support primes."""
    distance = {1: 0}
    frontier = [(0, 1)]
    while frontier:
        length, residue = heapq.heappop(frontier)
        if length != distance[residue]:
            continue
        for prime in primes:
            successor = residue * prime % modulus
            if length + 1 < distance.get(successor, modulus + 1):
                distance[successor] = length + 1
                heapq.heappush(frontier, (length + 1, successor))
    return distance


def exponent_deficit(m1: int, r: int) -> int:
    """Minimum added support-prime factors after an ordinary divisor to reach -1 mod r."""
    support = sorted(int(prime) for prime in sympy.factorint(m1))
    distances = support_word_distances(support, r)
    return min(
        distances[(-pow(int(divisor), -1, r)) % r]
        for divisor in sympy.divisors(m1)
    )


def run_audit(payload: dict[str, object]) -> dict[str, object]:
    """Compute the exact finite-exponent deficit at every stored first-r state."""
    records = []
    for record in payload["records"]:
        prime, r = int(record["prime"]), int(record["r"])
        m1 = (r * prime + 1) // 4
        deficit = exponent_deficit(m1, r)
        if (deficit == 0) != (int(record["minimum_overflow"]) == 1):
            raise AssertionError("zero deficit disagrees with the ordinary-divisor criterion")
        records.append(
            {
                "prime": prime,
                "r": r,
                "minimum_overflow": int(record["minimum_overflow"]),
                "exponent_deficit": deficit,
            }
        )
    histogram = Counter(int(record["exponent_deficit"]) for record in records)
    return {
        "arithmetic": (
            "BFS word distances in the residue subgroup generated by the prime support of "
            "M1, minimized after every actual ordinary divisor of M1"
        ),
        "scope_note": (
            "A finite exponent-deficit profile for stored first-r states. It neither "
            "constructs a new tail nor proves a uniform deficit bound generally."
        ),
        "prime_limit": payload["prime_limit"],
        "first_hit_count": len(records),
        "exponent_deficit_histogram": {str(key): value for key, value in sorted(histogram.items())},
        "maximum_exponent_deficit": max(histogram, default=None),
        "records": records,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    result = run_audit(json.loads(args.input.read_text(encoding="utf-8")))
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({key: value for key, value in result.items() if key != "records"}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
