#!/usr/bin/env python3
"""Measure the saturated-prime subgroup certificate on minimal-offset rays."""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path
import sys

import sympy


ROOT = Path(__file__).resolve().parents[1]
SHORT_CERTIFICATE = ROOT / "reproductions" / "short_certificate.py"
TARGETED_DESCENT = ROOT / "reproductions" / "type_ii_h19_targeted_quadratic_descent.py"
DEFAULT_INPUT = ROOT / "reproductions" / "type-ii-tail-shifted-quadratic-square-necessity-200m-results.json"
DEFAULT_OUTPUT = ROOT / "reproductions" / "type-ii-tail-shifted-quadratic-saturation-profile-200m-results.json"


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path.name}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


short_certificate = load_module("tail_shifted_saturation_short_certificate", SHORT_CERTIFICATE)
targeted_descent = load_module("tail_shifted_saturation_targeted_descent", TARGETED_DESCENT)


def saturated_subgroup_hit(L: int, t: int) -> dict[str, object]:
    """Test the sufficient subgroup generated by fully exponent-saturated primes.

    If q^a divides L and 2a >= ord_t(q)-1, the exponents 0,...,2a
    cover the whole cyclic subgroup generated by q. Their product is a
    certified subset of Pi_t(L^2), not an approximation to all of it.
    """
    target = (-L) % t
    residues = {1}
    saturated = []
    for prime, exponent in sympy.factorint(L).items():
        prime = int(prime)
        exponent = int(exponent)
        order = int(sympy.n_order(prime, t))
        if 2 * exponent < order - 1:
            continue
        saturated.append({"prime": prime, "exponent": exponent, "order": order})
        residues = {
            residue * pow(prime, power, t) % t
            for residue in residues
            for power in range(order)
        }
    return {
        "target_residue": target,
        "saturated_primes": saturated,
        "saturated_subgroup_size": len(residues),
        "saturated_subgroup_hits_target": target in residues,
    }


def ray_profile(prime: int, shift: int, spf) -> dict[str, object]:
    base = (prime - shift) // 4
    rows = []
    for k in short_certificate.positive_divisors_from_spf(base, spf):
        q = 4 * k - 1
        if q % shift:
            continue
        source = (q * prime + shift) // (q + 1)
        if (q + 1) * source != q * prime + shift or source % shift:
            raise AssertionError("stored minimal offset failed source normalization")
        t = q // shift
        L = k * (source // shift)
        row = saturated_subgroup_hit(L, t)
        row.update({"k": k, "source_distance": prime - source, "t": t, "L": L})
        rows.append(row)
    if not rows:
        raise AssertionError("minimal offset has no compatible k")
    hits = [row for row in rows if row["saturated_subgroup_hits_target"]]
    return {
        "prime": prime,
        "minimal_offset": shift,
        "square_tail_essential_at_minimal_offset": False,
        "compatible_k_count": len(rows),
        "saturated_subgroup_hit": bool(hits),
        "first_saturated_subgroup_hit": hits[0] if hits else None,
    }


def run_audit(payload: dict[str, object]) -> dict[str, object]:
    records_in = payload["records"]
    primes = [int(record["prime"]) for record in records_in]
    if not primes:
        raise ValueError("input has no minimal-offset rays")
    spf = targeted_descent.TrialSmallestFactors(max(primes))
    records = []
    for record in records_in:
        profile = ray_profile(int(record["prime"]), int(record["minimal_offset"]), spf)
        profile["square_tail_essential_at_minimal_offset"] = bool(
            record["square_tail_essential_at_minimal_offset"]
        )
        records.append(profile)
    hits = [record for record in records if record["saturated_subgroup_hit"]]
    square_hits = [record for record in hits if record["square_tail_essential_at_minimal_offset"]]
    return {
        "arithmetic": (
            "exact orders modulo t and explicit product of every fully exponent-saturated "
            "prime cyclic subgroup, over all k compatible with each stored minimal offset"
        ),
        "scope_note": (
            "This tests only a sufficient saturated-prime subgroup certificate. Failure does "
            "not rule out a bounded, unsaturated exponent combination in Pi_t(L^2)."
        ),
        "prime_limit": payload["prime_limit"],
        "minimal_offset_ray_count": len(records),
        "saturated_subgroup_hit_count": len(hits),
        "saturated_subgroup_hit_primes": [record["prime"] for record in hits],
        "square_essential_saturated_subgroup_hit_count": len(square_hits),
        "saturated_subgroup_miss_primes": [
            record["prime"] for record in records if not record["saturated_subgroup_hit"]
        ],
        "records": records,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    result = run_audit(json.loads(args.input.read_text(encoding="utf-8")))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({key: value for key, value in result.items() if key != "records"}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
