#!/usr/bin/env python3
"""Profile k=1 versus k>1 shared certificates after four automatic gaps."""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "reproductions" / "type-ii-automatic-residual-k1-funnel-10m-results.json"
GAP_23 = ROOT / "reproductions" / "type_ii_shared_gap_23_profile.py"


def load_gap_23():
    spec = importlib.util.spec_from_file_location(
        "type_ii_automatic_residual_k1_gap_23", GAP_23
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load type_ii_shared_gap_23_profile.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


gap_23 = load_gap_23()
short_certificate = gap_23.short_certificate


def prime_factorization_from_spf(value: int, spf: list[int]) -> dict[int, int]:
    """Return the prime factorization of a positive table-covered integer."""
    if value <= 0 or value >= len(spf):
        raise ValueError("SPF table does not cover the requested value")
    factors: dict[int, int] = {}
    while value > 1:
        prime = spf[value]
        exponent = 0
        while value % prime == 0:
            value //= prime
            exponent += 1
        factors[prime] = exponent
    return factors


def distinct_prime_factors_from_spf(value: int, spf: list[int]) -> list[int]:
    """Return the distinct prime factors of a positive table-covered integer."""
    return list(prime_factorization_from_spf(value, spf))


def unit_prime_factor_multiset_from_spf(
    value: int, modulus: int, spf: list[int]
) -> list[int]:
    """Return prime factors of value coprime to modulus, with multiplicity."""
    if modulus < 2:
        raise ValueError("modulus must be at least two")
    factors = prime_factorization_from_spf(value, spf)
    return [
        prime
        for prime, exponent in factors.items()
        if modulus % prime
        for _ in range(exponent)
    ]


def euler_phi_from_spf(value: int, spf: list[int]) -> int:
    """Compute Euler's totient of a positive table-covered integer."""
    if value < 1:
        raise ValueError("value must be positive")
    result = value
    for prime in prime_factorization_from_spf(value, spf):
        result -= result // prime
    return result


def prefix_product_one_divisor(
    factors: list[int], modulus: int
) -> int | None:
    """Construct a nonempty subproduct congruent to one by prefix collision."""
    prefix = 1
    first_prefix_index = {1: 0}
    exact_prefix_products = [1]
    for index, factor in enumerate(factors, start=1):
        prefix = prefix * factor % modulus
        exact_prefix_products.append(exact_prefix_products[-1] * factor)
        previous_index = first_prefix_index.get(prefix)
        if previous_index is not None:
            divisor = exact_prefix_products[index] // exact_prefix_products[
                previous_index
            ]
            if divisor <= 1 or divisor % modulus != 1:
                raise AssertionError("prefix collision did not produce a unit divisor")
            return divisor
        first_prefix_index[prefix] = index
    return None


def generated_unit_residue_subgroup(
    factors: list[int], modulus: int
) -> frozenset[int]:
    """Return the subgroup of units generated by the supplied factor residues."""
    subgroup = {1}
    for factor in sorted(set(factor % modulus for factor in factors)):
        if math.gcd(factor, modulus) != 1:
            raise ValueError("a subgroup generator must be a unit")
        powers = []
        power = 1
        while True:
            powers.append(power)
            power = power * factor % modulus
            if power == 1:
                break
        subgroup = {
            element * power % modulus
            for element in subgroup
            for power in powers
        }
    return frozenset(subgroup)


def p_group_davenport_data(
    subgroup: frozenset[int], modulus: int
) -> tuple[int, tuple[int, ...], int] | None:
    """Return the exact Davenport data when ``subgroup`` is an abelian p-group.

    For H = direct_sum C_(p**a_i), the p-group formula is
    D(H)=1+sum_i(p**a_i-1).  The exponents are recovered from the exact
    cardinalities of H[p**k], so no invariant-factor guess is used.
    """
    order = len(subgroup)
    if order == 1:
        return 1, (), 1
    remaining = order
    prime = None
    candidate = 2
    while candidate * candidate <= remaining:
        if remaining % candidate == 0:
            if prime is not None:
                return None
            prime = candidate
            while remaining % candidate == 0:
                remaining //= candidate
        candidate += 1
    if remaining > 1:
        if prime is not None:
            return None
        prime = remaining
    if prime is None:
        return None

    exponents_at_least: list[int] = []
    previous_log = 0
    prime_power = prime
    while True:
        torsion_count = sum(
            pow(element, prime_power, modulus) == 1 for element in subgroup
        )
        if torsion_count < 1 or torsion_count > order:
            raise AssertionError("invalid p-primary torsion count")
        log_count = 0
        count = torsion_count
        while count > 1:
            if count % prime:
                raise AssertionError("torsion count is not a p-power")
            count //= prime
            log_count += 1
        components_at_least = log_count - previous_log
        exponents_at_least.append(components_at_least)
        previous_log = log_count
        if torsion_count == order:
            break
        prime_power *= prime
        if prime_power > order * prime:
            raise AssertionError("p-primary torsion did not exhaust subgroup")

    exponents: list[int] = []
    for index, count_at_least in enumerate(exponents_at_least):
        next_count = (
            exponents_at_least[index + 1]
            if index + 1 < len(exponents_at_least)
            else 0
        )
        exponents.extend([index + 1] * (count_at_least - next_count))
    if prime ** sum(exponents) != order:
        raise AssertionError("recovered p-group exponents have wrong order")
    davenport = 1 + sum(prime**exponent - 1 for exponent in exponents)
    return prime, tuple(exponents), davenport


def integer_prime_factorization(value: int) -> dict[int, int]:
    """Factor a small positive integer without relying on the SPF table."""
    if value < 1:
        raise ValueError("value must be positive")
    factors: dict[int, int] = {}
    divisor = 2
    while divisor * divisor <= value:
        while value % divisor == 0:
            factors[divisor] = factors.get(divisor, 0) + 1
            value //= divisor
        divisor += 1
    if value > 1:
        factors[value] = factors.get(value, 0) + 1
    return factors


def primary_component_exponents(
    subgroup: frozenset[int],
    modulus: int,
    prime: int,
    primary_order: int,
) -> tuple[int, ...]:
    """Recover elementary-divisor exponents of one primary component."""
    if primary_order < 1:
        raise ValueError("primary order must be positive")
    exponents_at_least: list[int] = []
    previous_log = 0
    prime_power = prime
    while True:
        torsion_count = sum(
            pow(element, prime_power, modulus) == 1 for element in subgroup
        )
        if torsion_count < 1 or torsion_count > primary_order:
            raise AssertionError("invalid primary torsion count")
        log_count = 0
        count = torsion_count
        while count > 1:
            if count % prime:
                raise AssertionError("primary torsion count is not a prime power")
            count //= prime
            log_count += 1
        components_at_least = log_count - previous_log
        if components_at_least < 0:
            raise AssertionError("primary torsion dimensions decreased")
        exponents_at_least.append(components_at_least)
        previous_log = log_count
        if torsion_count == primary_order:
            break
        prime_power *= prime
        if prime_power > primary_order * prime:
            raise AssertionError("primary torsion did not exhaust subgroup")

    exponents: list[int] = []
    for index, count_at_least in enumerate(exponents_at_least):
        next_count = (
            exponents_at_least[index + 1]
            if index + 1 < len(exponents_at_least)
            else 0
        )
        if count_at_least < next_count:
            raise AssertionError("primary component counts are not nested")
        exponents.extend([index + 1] * (count_at_least - next_count))
    if prime ** sum(exponents) != primary_order:
        raise AssertionError("recovered primary exponents have wrong order")
    return tuple(exponents)


def abelian_invariant_factor_data(
    subgroup: frozenset[int], modulus: int
) -> tuple[tuple[int, ...], tuple[tuple[int, tuple[int, ...]], ...]]:
    """Recover invariant factors and primary exponents of a finite unit subgroup."""
    order = len(subgroup)
    if order == 1:
        return (1,), ()
    factorization = integer_prime_factorization(order)
    primary_data = tuple(
        (
            prime,
            primary_component_exponents(
                subgroup, modulus, prime, prime**exponent
            ),
        )
        for prime, exponent in sorted(factorization.items())
    )
    rank = max(len(exponents) for _, exponents in primary_data)
    invariant_factors = [1] * rank
    for prime, exponents in primary_data:
        padded = [0] * (rank - len(exponents)) + list(exponents)
        for index, exponent in enumerate(padded):
            invariant_factors[index] *= prime**exponent
    if any(
        invariant_factors[index + 1] % invariant_factors[index]
        for index in range(rank - 1)
    ):
        raise AssertionError("invariant factors are not nested")
    if math.prod(invariant_factors) != order:
        raise AssertionError("invariant factors have wrong order")
    return tuple(invariant_factors), primary_data


def rank_two_davenport_data(
    subgroup: frozenset[int], modulus: int
) -> tuple[tuple[int, ...], tuple[tuple[int, tuple[int, ...]], ...], int] | None:
    """Return exact Davenport data for cyclic or rank-two abelian subgroups."""
    invariant_factors, primary_data = abelian_invariant_factor_data(
        subgroup, modulus
    )
    if len(invariant_factors) > 2:
        return None
    davenport = 1 + sum(invariant - 1 for invariant in invariant_factors)
    return invariant_factors, primary_data, davenport


def nonempty_subproduct_one(factors: list[int], modulus: int) -> int | None:
    """Construct any nonempty subproduct equal to one modulo ``modulus``."""
    reachable: dict[int, tuple[int, int]] = {1: (1, 0)}
    for factor in factors:
        previous = tuple(reachable.items())
        for residue, (product, length) in previous:
            next_residue = residue * factor % modulus
            next_product = product * factor
            if next_residue == 1:
                if next_product <= 1 or next_product % modulus != 1:
                    raise AssertionError("subproduct witness is not nontrivial")
                return next_product
            if next_residue not in reachable:
                reachable[next_residue] = (next_product, length + 1)
    return None


def single_prime_shared_profile(
    records: list[dict[str, object]], gap_cap: int, spf: list[int]
) -> dict[str, object]:
    """Test whether a non-k=1 point has any one-prime shared certificate.

    A hit requires one legal gap with both a Type II certificate and a prime
    divisor q of p+m satisfying q == 1 modulo m. This is stronger than
    inspecting the least-gap shared witness returned by the main funnel.
    """
    by_least_gap: Counter[int] = Counter()
    hits: list[dict[str, int]] = []
    misses: list[int] = []
    for record in records:
        prime = int(record["prime"])
        candidates: list[tuple[int, int]] = []
        for gap in range(3, min(gap_cap, prime - 2) + 1, 4):
            certificate = short_certificate.type_ii_residue_certificate(
                prime, gap, spf
            )
            if certificate is None:
                continue
            for shared_prime in distinct_prime_factors_from_spf(prime + gap, spf):
                if shared_prime % gap != 1:
                    continue
                first_scale = (shared_prime - 1) // gap
                witness = short_certificate.type_ii_scaled_first_tail_deflation_witness(
                    prime, gap, first_scale, spf
                )
                if witness is None:
                    raise AssertionError("single-prime shared candidate did not lift")
                candidates.append((gap, shared_prime))
        if not candidates:
            misses.append(prime)
            continue
        gap, shared_prime = min(candidates)
        by_least_gap[gap] += 1
        hits.append(
            {
                "prime": prime,
                "gap": gap,
                "shared_prime": shared_prime,
                "first_scale": (shared_prime - 1) // gap,
            }
        )
    return {
        "arithmetic": (
            "complete legal-gap Type II certificate scan plus exact prime-factor "
            "checks of p+m and scaled-first certificate reconstruction"
        ),
        "scope_note": (
            "A miss rules out only one-prime shared divisors through the stated "
            "gap cap; a composite shared divisor may still work."
        ),
        "single_prime_shared_count": len(hits),
        "single_prime_shared_by_least_gap": dict(sorted(by_least_gap.items())),
        "single_prime_shared_hits": hits,
        "single_prime_shared_misses": misses,
    }


def subgroup_threshold_shared_profile(
    records: list[dict[str, object]], gap_cap: int, spf: list[int]
) -> dict[str, object]:
    """Apply the generated-subgroup prefix-product threshold at every gap."""
    witnesses: list[dict[str, int]] = []
    misses: list[int] = []
    for record in records:
        prime = int(record["prime"])
        candidates: list[tuple[int, int, int, int]] = []
        for gap in range(3, min(gap_cap, prime - 2) + 1, 4):
            certificate = short_certificate.type_ii_residue_certificate(
                prime, gap, spf
            )
            if certificate is None:
                continue
            factors = unit_prime_factor_multiset_from_spf(prime + gap, gap, spf)
            subgroup_order = len(generated_unit_residue_subgroup(factors, gap))
            if len(factors) < subgroup_order:
                continue
            shared_divisor = prefix_product_one_divisor(factors, gap)
            if shared_divisor is None:
                raise AssertionError("subgroup threshold did not force a divisor")
            first_scale = (shared_divisor - 1) // gap
            witness = short_certificate.type_ii_scaled_first_tail_deflation_witness(
                prime, gap, first_scale, spf
            )
            if witness is None:
                raise AssertionError("subgroup-threshold candidate did not lift")
            candidates.append((gap, shared_divisor, len(factors), subgroup_order))
        if not candidates:
            misses.append(prime)
            continue
        gap, shared_divisor, factor_count, subgroup_order = min(candidates)
        witnesses.append(
            {
                "prime": prime,
                "gap": gap,
                "shared_divisor": shared_divisor,
                "first_scale": (shared_divisor - 1) // gap,
                "unit_factor_multiplicity": factor_count,
                "generated_subgroup_order": subgroup_order,
            }
        )
    return {
        "arithmetic": (
            "complete legal-gap Type II certificate scan; factor residues "
            "generate a finite subgroup H, and at least |H| factors force a "
            "prefix-product collision within H"
        ),
        "scope_note": (
            "This is a sufficient condition only. A miss may still have a "
            "shared divisor through a shorter zero-product subsequence."
        ),
        "subgroup_threshold_shared_count": len(witnesses),
        "subgroup_threshold_shared_witnesses": witnesses,
        "subgroup_threshold_shared_misses": misses,
    }


def p_group_davenport_shared_profile(
    records: list[dict[str, object]], gap_cap: int, spf: list[int]
) -> dict[str, object]:
    """Apply the exact Davenport threshold for p-primary residue subgroups."""
    witnesses: list[dict[str, object]] = []
    misses: list[int] = []
    p_group_gap_count = 0
    threshold_eligible_gap_count = 0
    threshold_histogram: Counter[int] = Counter()
    group_prime_histogram: Counter[int] = Counter()
    for record in records:
        prime = int(record["prime"])
        candidates: list[tuple[int, int, int, int, int, int, tuple[int, ...]]] = []
        for gap in range(3, min(gap_cap, prime - 2) + 1, 4):
            certificate = short_certificate.type_ii_residue_certificate(
                prime, gap, spf
            )
            if certificate is None:
                continue
            factors = unit_prime_factor_multiset_from_spf(prime + gap, gap, spf)
            subgroup = generated_unit_residue_subgroup(factors, gap)
            davenport_data = p_group_davenport_data(subgroup, gap)
            if davenport_data is None:
                continue
            p_group_gap_count += 1
            group_prime, exponents, davenport = davenport_data
            threshold_histogram[davenport] += 1
            group_prime_histogram[group_prime] += 1
            if len(factors) < davenport:
                continue
            threshold_eligible_gap_count += 1
            shared_divisor = nonempty_subproduct_one(factors, gap)
            if shared_divisor is None:
                raise AssertionError("p-group Davenport threshold did not force a divisor")
            first_scale = (shared_divisor - 1) // gap
            witness = short_certificate.type_ii_scaled_first_tail_deflation_witness(
                prime, gap, first_scale, spf
            )
            if witness is None:
                raise AssertionError("p-group Davenport candidate did not lift")
            candidates.append(
                (
                    gap,
                    shared_divisor,
                    len(factors),
                    len(subgroup),
                    davenport,
                    group_prime,
                    exponents,
                )
            )
        if not candidates:
            misses.append(prime)
            continue
        (
            gap,
            shared_divisor,
            factor_count,
            subgroup_order,
            davenport,
            group_prime,
            exponents,
        ) = min(candidates)
        witnesses.append(
            {
                "prime": prime,
                "gap": gap,
                "shared_divisor": shared_divisor,
                "first_scale": (shared_divisor - 1) // gap,
                "unit_factor_multiplicity": factor_count,
                "generated_subgroup_order": subgroup_order,
                "p_group_prime": group_prime,
                "davenport_constant": davenport,
                "p_group_exponents": list(exponents),
            }
        )
    return {
        "arithmetic": (
            "complete legal-gap Type II certificate scan; for p-primary generated "
            "unit subgroups, exact H[p^k] counts recover the p-group Davenport constant "
            "and a dynamic subproduct witness"
        ),
        "scope_note": (
            "This is a sufficient condition only. It applies only when the generated "
            "residue subgroup is a finite abelian p-group; all other gaps remain outside "
            "this threshold."
        ),
        "p_group_davenport_shared_count": len(witnesses),
        "p_group_davenport_shared_witnesses": witnesses,
        "p_group_davenport_shared_misses": misses,
        "p_group_gap_count": p_group_gap_count,
        "threshold_eligible_gap_count": threshold_eligible_gap_count,
        "davenport_threshold_histogram": dict(sorted(threshold_histogram.items())),
        "p_group_prime_histogram": dict(sorted(group_prime_histogram.items())),
    }


def rank_two_davenport_shared_profile(
    records: list[dict[str, object]], gap_cap: int, spf: list[int]
) -> dict[str, object]:
    """Apply the exact Davenport threshold for abelian groups of rank at most two."""
    witnesses: list[dict[str, object]] = []
    misses: list[int] = []
    rank_two_gap_count = 0
    threshold_eligible_gap_count = 0
    rank_histogram: Counter[int] = Counter()
    threshold_histogram: Counter[int] = Counter()
    invariant_factor_histogram: Counter[tuple[int, ...]] = Counter()
    for record in records:
        prime = int(record["prime"])
        candidates: list[
            tuple[
                int,
                int,
                int,
                tuple[int, ...],
                int,
                tuple[tuple[int, tuple[int, ...]], ...],
            ]
        ] = []
        for gap in range(3, min(gap_cap, prime - 2) + 1, 4):
            certificate = short_certificate.type_ii_residue_certificate(
                prime, gap, spf
            )
            if certificate is None:
                continue
            factors = unit_prime_factor_multiset_from_spf(prime + gap, gap, spf)
            subgroup = generated_unit_residue_subgroup(factors, gap)
            davenport_data = rank_two_davenport_data(subgroup, gap)
            if davenport_data is None:
                continue
            invariant_factors, primary_data, davenport = davenport_data
            rank_two_gap_count += 1
            rank = len(invariant_factors)
            rank_histogram[rank] += 1
            threshold_histogram[davenport] += 1
            invariant_factor_histogram[invariant_factors] += 1
            if len(factors) < davenport:
                continue
            threshold_eligible_gap_count += 1
            shared_divisor = nonempty_subproduct_one(factors, gap)
            if shared_divisor is None:
                raise AssertionError(
                    "rank-two Davenport threshold did not force a divisor"
                )
            first_scale = (shared_divisor - 1) // gap
            witness = short_certificate.type_ii_scaled_first_tail_deflation_witness(
                prime, gap, first_scale, spf
            )
            if witness is None:
                raise AssertionError("rank-two Davenport candidate did not lift")
            candidates.append(
                (
                    gap,
                    shared_divisor,
                    len(factors),
                    invariant_factors,
                    davenport,
                    primary_data,
                )
            )
        if not candidates:
            misses.append(prime)
            continue
        (
            gap,
            shared_divisor,
            factor_count,
            invariant_factors,
            davenport,
            primary_data,
        ) = min(candidates)
        witnesses.append(
            {
                "prime": prime,
                "gap": gap,
                "shared_divisor": shared_divisor,
                "first_scale": (shared_divisor - 1) // gap,
                "unit_factor_multiplicity": factor_count,
                "generated_subgroup_order": math.prod(invariant_factors),
                "invariant_factors": list(invariant_factors),
                "davenport_constant": davenport,
                "primary_components": [
                    {"prime": group_prime, "exponents": list(exponents)}
                    for group_prime, exponents in primary_data
                ],
            }
        )
    return {
        "arithmetic": (
            "complete legal-gap Type II certificate scan; invariant factors are "
            "recovered from exact primary torsion counts, and the rank-at-most-two "
            "Davenport formula is followed by a dynamic subproduct witness"
        ),
        "scope_note": (
            "This is a sufficient condition only. It applies to cyclic or rank-two "
            "generated residue subgroups; groups of rank at least three remain outside "
            "this threshold."
        ),
        "rank_two_davenport_shared_count": len(witnesses),
        "rank_two_davenport_shared_witnesses": witnesses,
        "rank_two_davenport_shared_misses": misses,
        "rank_two_gap_count": rank_two_gap_count,
        "threshold_eligible_gap_count": threshold_eligible_gap_count,
        "rank_histogram": dict(sorted(rank_histogram.items())),
        "davenport_threshold_histogram": dict(sorted(threshold_histogram.items())),
        "invariant_factor_histogram": {
            ",".join(str(value) for value in invariant_factors): count
            for invariant_factors, count in sorted(invariant_factor_histogram.items())
        },
    }


def totient_threshold_shared_profile(
    records: list[dict[str, object]], gap_cap: int, spf: list[int]
) -> dict[str, object]:
    """Apply the elementary phi(m) prefix-product threshold at every gap."""
    witnesses: list[dict[str, int]] = []
    misses: list[int] = []
    for record in records:
        prime = int(record["prime"])
        candidates: list[tuple[int, int, int, int]] = []
        for gap in range(3, min(gap_cap, prime - 2) + 1, 4):
            certificate = short_certificate.type_ii_residue_certificate(
                prime, gap, spf
            )
            if certificate is None:
                continue
            factors = unit_prime_factor_multiset_from_spf(prime + gap, gap, spf)
            threshold = euler_phi_from_spf(gap, spf)
            if len(factors) < threshold:
                continue
            shared_divisor = prefix_product_one_divisor(factors, gap)
            if shared_divisor is None:
                raise AssertionError("totient threshold did not force a divisor")
            first_scale = (shared_divisor - 1) // gap
            witness = short_certificate.type_ii_scaled_first_tail_deflation_witness(
                prime, gap, first_scale, spf
            )
            if witness is None:
                raise AssertionError("totient-threshold candidate did not lift")
            candidates.append((gap, shared_divisor, len(factors), threshold))
        if not candidates:
            misses.append(prime)
            continue
        gap, shared_divisor, factor_count, threshold = min(candidates)
        witnesses.append(
            {
                "prime": prime,
                "gap": gap,
                "shared_divisor": shared_divisor,
                "first_scale": (shared_divisor - 1) // gap,
                "unit_factor_multiplicity": factor_count,
                "totient_threshold": threshold,
            }
        )
    return {
        "arithmetic": (
            "complete legal-gap Type II certificate scan; at a gap with at "
            "least phi(m) prime factors of p+m coprime to m, prefix-product "
            "collision constructs a nontrivial divisor congruent to one"
        ),
        "scope_note": (
            "This is a sufficient condition only. A miss may still have a "
            "shared divisor through a shorter or non-prefix subproduct."
        ),
        "totient_threshold_shared_count": len(witnesses),
        "totient_threshold_shared_witnesses": witnesses,
        "totient_threshold_shared_misses": misses,
    }


def prime_power_shared_profile(
    records: list[dict[str, object]], gap_cap: int, spf: list[int]
) -> dict[str, object]:
    """Profile shared certificates whose divisor is one prime power.

    The profile considers every q^e dividing p+m, including e=1.
    It separately records points rescued by a proper prime power after all
    one-prime candidates have failed.
    """
    by_least_gap: Counter[int] = Counter()
    hits: list[dict[str, int]] = []
    proper_power_hits: list[dict[str, int]] = []
    proper_power_rescues: list[dict[str, int]] = []
    misses: list[int] = []
    for record in records:
        prime = int(record["prime"])
        candidates: list[tuple[int, int, int, int]] = []
        prime_candidates: list[tuple[int, int, int, int]] = []
        proper_power_candidates: list[tuple[int, int, int, int]] = []
        for gap in range(3, min(gap_cap, prime - 2) + 1, 4):
            certificate = short_certificate.type_ii_residue_certificate(
                prime, gap, spf
            )
            if certificate is None:
                continue
            for base, exponent in prime_factorization_from_spf(prime + gap, spf).items():
                power = 1
                for power_exponent in range(1, exponent + 1):
                    power *= base
                    if power % gap != 1:
                        continue
                    first_scale = (power - 1) // gap
                    witness = short_certificate.type_ii_scaled_first_tail_deflation_witness(
                        prime, gap, first_scale, spf
                    )
                    if witness is None:
                        raise AssertionError(
                            "prime-power shared candidate did not lift"
                        )
                    candidate = (gap, power, base, power_exponent)
                    candidates.append(candidate)
                    if power_exponent == 1:
                        prime_candidates.append(candidate)
                    else:
                        proper_power_candidates.append(candidate)
        if not candidates:
            misses.append(prime)
            continue
        gap, power, base, exponent = min(candidates)
        by_least_gap[gap] += 1
        hits.append(
            {
                "prime": prime,
                "gap": gap,
                "shared_prime_power": power,
                "base_prime": base,
                "exponent": exponent,
                "first_scale": (power - 1) // gap,
            }
        )
        if proper_power_candidates:
            gap, power, base, exponent = min(proper_power_candidates)
            proper_power_hits.append(
                {
                    "prime": prime,
                    "gap": gap,
                    "shared_prime_power": power,
                    "base_prime": base,
                    "exponent": exponent,
                    "first_scale": (power - 1) // gap,
                }
            )
            if not prime_candidates:
                proper_power_rescues.append(proper_power_hits[-1])
    return {
        "arithmetic": (
            "complete legal-gap Type II certificate scan plus exact "
            "prime-power factor checks of p+m and scaled-first certificate "
            "reconstruction"
        ),
        "scope_note": (
            "A miss rules out only one-prime-power shared divisors through "
            "the stated gap cap; a divisor involving multiple distinct "
            "primes may still work."
        ),
        "prime_power_shared_count": len(hits),
        "prime_power_shared_by_least_gap": dict(sorted(by_least_gap.items())),
        "prime_power_shared_hits": hits,
        "proper_prime_power_shared_count": len(proper_power_hits),
        "proper_prime_power_shared_hits": proper_power_hits,
        "proper_prime_power_rescues_after_single_prime_miss": proper_power_rescues,
        "prime_power_shared_misses": misses,
    }


def multi_prime_support_profile(
    records: list[dict[str, object]], gap_cap: int, spf: list[int]
) -> dict[str, object]:
    """Find the smallest distinct-prime support of every shared certificate."""
    support_histogram: Counter[int] = Counter()
    witnesses: list[dict[str, int]] = []
    misses: list[int] = []
    for record in records:
        prime = int(record["prime"])
        candidates: list[tuple[int, int, int]] = []
        for gap in range(3, min(gap_cap, prime - 2) + 1, 4):
            certificate = short_certificate.type_ii_residue_certificate(
                prime, gap, spf
            )
            if certificate is None:
                continue
            for shared_divisor in short_certificate.positive_divisors_from_spf(
                prime + gap, spf
            ):
                if shared_divisor == 1 or (shared_divisor - 1) % gap:
                    continue
                first_scale = (shared_divisor - 1) // gap
                witness = short_certificate.type_ii_scaled_first_tail_deflation_witness(
                    prime, gap, first_scale, spf
                )
                if witness is None:
                    raise AssertionError("shared-divisor candidate did not lift")
                support_size = len(
                    prime_factorization_from_spf(shared_divisor, spf)
                )
                candidates.append((support_size, gap, shared_divisor))
        if not candidates:
            misses.append(prime)
            continue
        support_size, gap, shared_divisor = min(candidates)
        support_histogram[support_size] += 1
        witnesses.append(
            {
                "prime": prime,
                "minimum_distinct_prime_support": support_size,
                "gap": gap,
                "shared_divisor": shared_divisor,
                "first_scale": (shared_divisor - 1) // gap,
            }
        )
    return {
        "arithmetic": (
            "complete legal-gap Type II certificate scan, exhaustive divisor "
            "enumeration of p+m, exact factor support counts, and scaled-first "
            "certificate reconstruction"
        ),
        "scope_note": (
            "The minimum is over shared certificates through the stated gap "
            "cap; it does not assert a uniform all-prime bound."
        ),
        "minimum_distinct_prime_support_histogram": dict(
            sorted(support_histogram.items())
        ),
        "minimum_distinct_prime_support_witnesses": witnesses,
        "minimum_distinct_prime_support_misses": misses,
    }


def minimum_factor_length_profile(
    records: list[dict[str, object]], gap_cap: int, spf: list[int]
) -> dict[str, object]:
    """Find the shortest prime-factor zero product in every shared certificate."""
    length_histogram: Counter[int] = Counter()
    witnesses: list[dict[str, int]] = []
    misses: list[int] = []
    for record in records:
        prime = int(record["prime"])
        candidates: list[tuple[int, int, int]] = []
        for gap in range(3, min(gap_cap, prime - 2) + 1, 4):
            certificate = short_certificate.type_ii_residue_certificate(
                prime, gap, spf
            )
            if certificate is None:
                continue
            for shared_divisor in short_certificate.positive_divisors_from_spf(
                prime + gap, spf
            ):
                if shared_divisor == 1 or (shared_divisor - 1) % gap:
                    continue
                first_scale = (shared_divisor - 1) // gap
                witness = short_certificate.type_ii_scaled_first_tail_deflation_witness(
                    prime, gap, first_scale, spf
                )
                if witness is None:
                    raise AssertionError("shared-divisor candidate did not lift")
                factor_length = sum(
                    prime_factorization_from_spf(shared_divisor, spf).values()
                )
                candidates.append((factor_length, gap, shared_divisor))
        if not candidates:
            misses.append(prime)
            continue
        factor_length, gap, shared_divisor = min(candidates)
        length_histogram[factor_length] += 1
        witnesses.append(
            {
                "prime": prime,
                "minimum_factor_multiplicity": factor_length,
                "gap": gap,
                "shared_divisor": shared_divisor,
                "first_scale": (shared_divisor - 1) // gap,
            }
        )
    return {
        "arithmetic": (
            "complete legal-gap Type II certificate scan, exhaustive divisor "
            "enumeration of p+m, factor multiplicity counts, and scaled-first "
            "certificate reconstruction"
        ),
        "scope_note": (
            "The minimum is over shared certificates through the stated gap "
            "cap; it is not a uniform all-prime zero-product bound."
        ),
        "minimum_factor_multiplicity_histogram": dict(sorted(length_histogram.items())),
        "minimum_factor_multiplicity_witnesses": witnesses,
        "minimum_factor_multiplicity_misses": misses,
    }


def run_audit(
    limit: int,
    gap_cap: int = 239,
    include_single_prime_profile: bool = False,
    include_subgroup_threshold_profile: bool = False,
    include_p_group_davenport_profile: bool = False,
    include_rank_two_davenport_profile: bool = False,
    include_totient_threshold_profile: bool = False,
    include_prime_power_profile: bool = False,
    include_support_profile: bool = False,
    include_factor_length_profile: bool = False,
) -> dict[str, object]:
    """Run the exact four-auto-gap residual funnel through k=1 and k>1."""
    if limit < 73 or gap_cap < 3:
        raise ValueError("limit must be at least 73 and gap_cap at least 3")
    spf = short_certificate.smallest_prime_factors(limit + gap_cap)
    counts = {
        "four_auto_gap_residual": 0,
        "k1_hit": 0,
        "non_k1": 0,
        "non_k1_shared_hit": 0,
    }
    scale_histogram: Counter[int] = Counter()
    non_k1_records = []
    core_prime_count = 0
    for prime in short_certificate.primes_up_to(limit):
        if prime % 24 != 1:
            continue
        core_prime_count += 1
        if gap_23.profile_prime(prime, spf).category != "no_type_ii_3_7_11_23":
            continue
        counts["four_auto_gap_residual"] += 1
        k1_witness = short_certificate.first_type_ii_tail_deflation_witness(
            prime, spf
        )
        if k1_witness is not None:
            counts["k1_hit"] += 1
            continue
        counts["non_k1"] += 1
        witness = short_certificate.type_ii_shared_divisor_tail_deflation_scan(
            prime, gap_cap, spf
        )
        if witness is None:
            non_k1_records.append({"prime": prime, "witness": None})
            continue
        counts["non_k1_shared_hit"] += 1
        scale_histogram[witness.first_scale] += 1
        non_k1_records.append(
            {
                "prime": prime,
                "gap": witness.gap,
                "first_scale": witness.first_scale,
                "shared_divisor": witness.first_scale * witness.gap + 1,
                "certificate_divisor": witness.certificate.divisor,
            }
        )
    if counts["four_auto_gap_residual"] != counts["k1_hit"] + counts["non_k1"]:
        raise AssertionError("k=1 partition was inconsistent")
    result: dict[str, object] = {
        "arithmetic": (
            "exact SPF factorization, complete k=1 p-1 divisor scan, and "
            "unbounded-first-scale shared-divisor scan through the gap cap"
        ),
        "scope_note": (
            "This is a finite residual funnel. k>1 witnesses remain marked "
            "Type II representations rather than unmarked descent steps."
        ),
        "prime_limit": limit,
        "gap_cap": gap_cap,
        "core_prime_count": core_prime_count,
        "counts": counts,
        "non_k1_scale_histogram": dict(sorted(scale_histogram.items())),
        "non_k1_records": non_k1_records,
    }
    if include_single_prime_profile:
        result["single_prime_shared_profile"] = single_prime_shared_profile(
            non_k1_records, gap_cap, spf
        )
    if include_subgroup_threshold_profile:
        result["subgroup_threshold_shared_profile"] = subgroup_threshold_shared_profile(
            non_k1_records, gap_cap, spf
        )
    if include_p_group_davenport_profile:
        result["p_group_davenport_shared_profile"] = p_group_davenport_shared_profile(
            non_k1_records, gap_cap, spf
        )
    if include_rank_two_davenport_profile:
        result["rank_two_davenport_shared_profile"] = rank_two_davenport_shared_profile(
            non_k1_records, gap_cap, spf
        )
    if include_totient_threshold_profile:
        result["totient_threshold_shared_profile"] = totient_threshold_shared_profile(
            non_k1_records, gap_cap, spf
        )
    if include_prime_power_profile:
        result["prime_power_shared_profile"] = prime_power_shared_profile(
            non_k1_records, gap_cap, spf
        )
    if include_support_profile:
        result["multi_prime_support_profile"] = multi_prime_support_profile(
            non_k1_records, gap_cap, spf
        )
    if include_factor_length_profile:
        result["minimum_factor_length_profile"] = minimum_factor_length_profile(
            non_k1_records, gap_cap, spf
        )
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=10_000_000)
    parser.add_argument("--gap-cap", type=int, default=239)
    parser.add_argument(
        "--single-prime-profile",
        action="store_true",
        help="also scan every legal gap for a one-prime shared divisor",
    )
    parser.add_argument(
        "--totient-threshold-profile",
        action="store_true",
        help="also apply the phi(m) unit-factor prefix-product threshold",
    )
    parser.add_argument(
        "--subgroup-threshold-profile",
        action="store_true",
        help="also apply the generated-unit-subgroup prefix-product threshold",
    )
    parser.add_argument(
        "--p-group-davenport-profile",
        action="store_true",
        help="also apply the exact Davenport threshold for p-primary unit subgroups",
    )
    parser.add_argument(
        "--rank-two-davenport-profile",
        action="store_true",
        help="also apply the exact Davenport threshold for rank-at-most-two subgroups",
    )
    parser.add_argument(
        "--prime-power-profile",
        action="store_true",
        help="also scan every legal gap for a one-prime-power shared divisor",
    )
    parser.add_argument(
        "--support-profile",
        action="store_true",
        help="also compute the minimum distinct-prime support of a shared divisor",
    )
    parser.add_argument(
        "--factor-length-profile",
        action="store_true",
        help="also compute the minimum prime-factor multiplicity of a shared divisor",
    )
    parser.add_argument("--output", type=Path, default=RESULTS)
    args = parser.parse_args()
    payload = run_audit(
        args.limit,
        args.gap_cap,
        include_single_prime_profile=args.single_prime_profile,
        include_subgroup_threshold_profile=args.subgroup_threshold_profile,
        include_p_group_davenport_profile=args.p_group_davenport_profile,
        include_rank_two_davenport_profile=args.rank_two_davenport_profile,
        include_totient_threshold_profile=args.totient_threshold_profile,
        include_prime_power_profile=args.prime_power_profile,
        include_support_profile=args.support_profile,
        include_factor_length_profile=args.factor_length_profile,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
