#!/usr/bin/env python3
"""Classify fourth-pressure-point tail misses by subgroup or exponent obstruction."""

from __future__ import annotations

import argparse
import json
import math
from collections import Counter
from pathlib import Path

import sympy
from sympy import Matrix
from sympy.matrices.normalforms import hermite_normal_form


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = (
    ROOT / "reproductions" / "type-ii-h19-fourth-even-source-tail-profile-640775689-results.json"
)
DEFAULT_OUTPUT = (
    ROOT / "reproductions" / "type-ii-h19-fourth-even-source-subgroup-profile-640775689-results.json"
)


def unit_exponent_vector(modulus: int, value: int) -> tuple[list[int], list[int]]:
    """Express a unit in the cyclic unit group of every odd prime-power CRT factor."""
    if math.gcd(modulus, value) != 1:
        raise ValueError("value must be a unit modulo modulus")
    exponents: list[int] = []
    orders: list[int] = []
    for prime, power in sorted(sympy.factorint(modulus).items()):
        component = int(prime) ** int(power)
        generator = sympy.primitive_root(component)
        if generator is None:
            raise AssertionError("odd prime-power unit group lacks a primitive root")
        orders.append(int(sympy.totient(component)))
        exponents.append(int(sympy.discrete_log(component, value % component, generator)))
    return exponents, orders


def target_in_generated_subgroup(
    modulus: int, generators: list[int], target: int
) -> tuple[bool, int, int]:
    """Test subgroup membership by HNF in the CRT discrete-log coordinates."""
    target_vector, orders = unit_exponent_vector(modulus, target)
    generator_vectors = [
        unit_exponent_vector(modulus, generator)[0] for generator in generators
    ]
    lattice = Matrix(
        [
            [
                *(vector[row] for vector in generator_vectors),
                *(orders[row] if row == column else 0 for column in range(len(orders))),
            ]
            for row in range(len(orders))
        ]
    )
    basis = hermite_normal_form(lattice)
    coordinates = basis.inv() * Matrix(target_vector)
    subgroup_index = int(abs(basis.det()))
    ambient_order = math.prod(orders)
    if ambient_order % subgroup_index:
        raise AssertionError("HNF lattice index does not divide the unit group order")
    return (
        all(coordinate.q == 1 for coordinate in coordinates),
        subgroup_index,
        ambient_order // subgroup_index,
    )


def run_profile(payload: dict[str, object]) -> dict[str, object]:
    """Separate all square-tail failures into character and finite-product types."""
    records: list[dict[str, object]] = []
    for ray in payload["rays"]:
        modulus = int(ray["r"])
        m1 = int(ray["m1"])
        target = (-m1) % modulus
        generators = sorted(
            set(sympy.factorint(int(ray["k"]))) | set(sympy.factorint(int(ray["s"])))
        )
        inside, index, subgroup_order = target_in_generated_subgroup(
            modulus, generators, target
        )
        actual_hit = int(ray["target_residue_factor_count"]) > 0
        if actual_hit and not inside:
            raise AssertionError("a square-tail hit must lie in the generated subgroup")
        kind = (
            "hit"
            if actual_hit
            else "finite-product-set"
            if inside
            else "subgroup-character"
        )
        records.append(
            {
                "distance": int(ray["distance"]),
                "r": modulus,
                "target_residue": target,
                "generator_primes": generators,
                "generated_subgroup_index": index,
                "generated_subgroup_order": subgroup_order,
                "target_in_generated_subgroup": inside,
                "tail_residue_factor_count": int(ray["target_residue_factor_count"]),
                "classification": kind,
            }
        )
    histogram = Counter(record["classification"] for record in records)
    return {
        "arithmetic": (
            "exact prime-power CRT discrete logarithms and Hermite-normal-form "
            "membership in the unit subgroup generated by the M1 prime factors"
        ),
        "scope_note": (
            "A finite one-prime classification. Character-type and finite-product "
            "obstructions are separated, but neither class is universally closed."
        ),
        "prime": payload["prime"],
        "tail_ray_count": len(records),
        "classification_counts": dict(sorted(histogram.items())),
        "records": records,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    payload = json.loads(args.input.read_text(encoding="utf-8"))
    result = run_profile(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
